### ISSUE TITLE
Problems on compiling ppafm in Win11

### ISSUE THREAD

**Issue by lycheehoo** [Probe-Particle/ppafm#110]
![Snipaste_2023-03-09_10-38-40](https://user-images.githubusercontent.com/117914902/223901737-99ce7eb1-3776-4eb2-836d-95a8a484bd7d.png)
Dear editor,
I was trying to compile these ppafm codes in Win11 through your installation guide, but when I navigated to cpp folder and compiled with the following command: mingw32-make, it displayed an error as shown below.

**Comment by NikoOinonen** [comment]
Windows support is something that we are figuring out at the moment. There should be pre-built pip wheels available (hopefully) soon. In the meanwhile, the best way would be to follow the instructions at https://github.com/Probe-Particle/ppafm#building-the-code and build it using the Microsoft Visual Studio compiler. I have tested that it works on Win10 but not on Win11.

**Comment by lycheehoo** [comment]
> Windows support is something that we are figuring out at the moment. There should be pre-built pip wheels available (hopefully) soon. In the meanwhile, the best way would be to follow the instructions at https://github.com/Probe-Particle/ppafm#building-the-code and build it using the Microsoft Visual Studio compiler. I have tested that it works on Win10 but not on Win11.

Thanks for your reply. I tried to build these codes using Microsoft Visual Studio compiler, but errors come up as below. I do not know if it depends on Win10 or Win11. Besides, I wonder how it looks like running in GUI, is that contains specific icons and buttons so that we can just click on them to get the simulated AFM images? 


`RuntimeError:` Could not find VsDevCmd.bat

ERROR Backend subprocess exited when trying to invoke `

**Comment by NikoOinonen** [comment]
Did you install the Visual Studio Tools from here: https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2022, and check the option for "Desktop development with C++"?  This should install the `VsDevCmd.bat` that it's asking for. If you did, then it could be that the location for that script is somewhere else on Win11, which needs to be taken into account during the build.

The documentation for the GUI is lacking at the moment. It should work on Windows as well if you can get the pip package installed.

**Comment by lycheehoo** [comment]
Fine. I successfully built these codes on win11 and got ppafm-0.2.0a1.tar.gz and ppafm-0.2.0a1-cp310-cp310-win32.whl, so what is the next process and how to use them? Honestly, I am just a coding beginner, thanks for your patient reply.

**Comment by NikoOinonen** [comment]
You can install the package with pip using the built .whl. If you want to use the GUI, then you also need to specify the optional `[opencl]` dependency. So you could do
```bash
pip install ppafm-0.2.0a1-cp310-cp310-win32.whl[opencl]
```
I recommend doing the installation with administrative rights, so that all of the paths are set correctly automatically (Command Prompt->right-click->Run as administrator).

>  Honestly, I am just a coding beginner

That's okay, just ask if something is unclear. Really, the goal is that you would not have to do all of this manual compilation when the automated builds are working, eventually. Everything is kind of in flux here right now, so the documentation is outdated as well.

**Comment by lycheehoo** [comment]
Thanks, I think this is a good opportunity for me to take the first step. I try to install `.whl` as your advised, but it shows below.

```
(venv) PS F:\ppafm-main\dist> pip install .\ppafm-0.2.0a1-cp310-cp310-win32.whl[opencl]
ERROR: ppafm-0.2.0a1-cp310-cp310-win32.whl is not a supported wheel on this platform.
```

And I checked my platform:

```
>>> platform.architecture()
('64bit', 'WindowsPE')
```

What is the solution?

**Comment by NikoOinonen** [comment]
Hmm, for some reason the compiled `.whl` is for 32bit platform. I specifically put the flag for the 64bit platform into the setup at https://github.com/Probe-Particle/ppafm/blob/74180f913ec13805947bc124f40dd3acd30c0587/setup.py#L36, so I don't know why that is happening.

You could also try installing with just running
```bash
pip install .[opencl]
```
in the repository root.

**Comment by NikoOinonen** [comment]
@lycheehoo I'm not sure what exactly you mean, but the `.xyz` file format can only contain atomic coordinates, not lattice coordinates. The accompanying `params.ini` does contain the lattice vectors, which are used if you run the example with `run.sh`, and the resulting images are periodic in the lattice. If you open it in the GUI, the lattice vectors are not there, but they can be inputted into the boxes under "Periodic Boundaries".

Since you are asking this, can I assume that you got it installed in the end?

**Comment by lycheehoo** [comment]
Thanks, I got it. I have to say not yet. To be specific, opencl has been successfully installed in brantch `ppafm-main`  as below, `Successfully installed MarkupSafe-2.1.2 ase-3.22.1 funcsigs-1.0.2 mako-1.2.4 platformdirs-3.1.1 ppafm-0.2.0a1 pyopencl-2022.3.1 pytools-2022.1.14 reikna-0.8.0 scipy-1.10.1 typing_extensions-4.5.0` 
but I dont know how to "invoke" the GUI window as the `README.md` said :
`Run the GUI application:
./GUI/ppm-gui`

**Comment by NikoOinonen** [comment]
Ah, that part is outdated as well. Apologies for that.

If the installation is correct and the paths are set correctly, the way to run it is to just run
```
ppafm-gui
```
from anywhere on the command line.

**Comment by lycheehoo** [comment]
You are so kind. I have met new trouble, could you give me some advice please?

`(pp_test) F:\ppafm-main>ppafm-gui
 PACKAGE_PATH =  D:\Anaconda3\envs\pp_test\Lib\site-packages\ppafm
 CPP_PATH     =  D:\Anaconda3\envs\pp_test\Lib\site-packages\ppafm\cpp
Traceback (most recent call last):
  File "D:\Anaconda3\envs\pp_test\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\pp_test\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\pp_test\Scripts\ppafm-gui.exe\__main__.py", line 4, in <module>
  File "D:\Anaconda3\envs\pp_test\lib\site-packages\ppafm\cli\gui\ppafm_gui.py", line 20, in <module>
    import ppafm.GridUtils as GU
  File "D:\Anaconda3\envs\pp_test\lib\site-packages\ppafm\GridUtils.py", line 17, in <module>
    lib = cpp_utils.get_cdll('GU')
  File "D:\Anaconda3\envs\pp_test\lib\site-packages\ppafm\cpp_utils.py", line 53, in get_cdll
    raise RuntimeError(f"Could not find compiled extension module in `{module_path}`. "
RuntimeError: Could not find compiled extension module in `D:\Anaconda3\envs\pp_test\Lib\site-packages\ppafm\cpp\GridUtils_lib.dll`. Either check pip installation or enable dynamic compilation by setting the environment variable PPAFM_RECOMPILE=1`

**Comment by lycheehoo** [comment]
Besides, when I run the tset file `Graphene-spline`, the error and relevant codes show as below.
```
File "/public4/home/sc53074/.conda/envs/python37/lib/python3.7/site-packages/ppafm/GridUtils.py", line 235, in loadXSF
    filein = open( fname )
FileNotFoundError: [Errno 2] No such file or directory: 'OutFz.xsf'
```

relevent codes in `GridUtils.py`:
```
def loadXSF(fname, xyz_order=False, verbose=True):
	filein = open( fname )
	startline, head = readUpTo(filein, "BEGIN_DATAGRID_3D")
```

**Comment by NikoOinonen** [comment]
> (pp_test) F:\ppafm-main>ppafm-gui PACKAGE_PATH =  D:\Anaconda3\envs\pp_test\Lib\site-packages\ppafm CPP_PATH     =  D:\Anaconda3\envs\pp_test\Lib\site-packages\ppafm\cpp Traceback (most recent call last): File "D:\Anaconda3\envs\pp_test\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "D:\Anaconda3\envs\pp_test\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "D:\Anaconda3\envs\pp_test\Scripts\ppafm-gui.exe\__main__.py", line 4, in <module> File "D:\Anaconda3\envs\pp_test\lib\site-packages\ppafm\cli\gui\ppafm_gui.py", line 20, in <module> import ppafm.GridUtils as GU File "D:\Anaconda3\envs\pp_test\lib\site-packages\ppafm\GridUtils.py", line 17, in <module> lib = cpp_utils.get_cdll('GU') File "D:\Anaconda3\envs\pp_test\lib\site-packages\ppafm\cpp_utils.py", line 53, in get_cdll raise RuntimeError(f"Could not find compiled extension module in {module_path}. " RuntimeError: Could not find compiled extension module in D:\Anaconda3\envs\pp_test\Lib\site-packages\ppafm\cpp\GridUtils_lib.dll. Either check pip installation or enable dynamic compilation by setting the environment variable PPAFM_RECOMPILE=1

This should not happen if the extensions got build correctly during the install. Did you manage to run the graphene example? If you did, then it's very odd, since that file (`D:\Anaconda3\envs\pp_test\Lib\site-packages\ppafm\cpp\GridUtils_lib.dll`) is required both for running the cpu-only examples and the GUI.

You could try doing as it says and set the `PPAFM_RECOMPILE` variable to `1`: 
```
set PPAFM_RECOMPILE=1
```
and try running it again.

**Comment by lycheehoo** [comment]
OK, I have tried as you advised, but it still got errors, and I will try to figure it out later. By the way, how to change the values of `Tip_x`  `Tip_y` `Tip_z` in simulated images?

**Comment by NikoOinonen** [comment]
You can also find some information on how the tip position is defined on this wiki page: https://github.com/Probe-Particle/ppafm/wiki/Technical-details#reference-frame-of-the-grids

**Comment by alexriss** [comment]
I have it running on my Windows machine. There are a few things I did (the `:xx` notation specifies the respective line numbers in the files):

- install `make` and `mingw`. This can be done via [choco](https://chocolatey.org/).
- change `cpp_utils:17`
   ```lib_ext = '_lib.so'```
- change `cpp_utils.py:58`: add `winmode=0`, i.e.:
    ```return ctypes.CDLL(str(module_path), winmode=0)```
- change `oclUntils.py:26` to account for spaces in the path:
	```program = cl.Program(self.ctx, fstr ).build(options=['-I', '"' + self.CL_PATH + '"'])```
- uncomment `fastmath_light.h:9`:
  ```#define M_PI          3.14159265358979323846```
- run the `python -m build` command in the ppafm folder. first you might need to install the `build` module with `pip install build`.
- as admin, run the `pip install dist/....whl[opencl]` command.
- manually run `make` in the cpp directory of the installation (in `<python-dir>\Lib\site-packages\ppafm\cpp`. With my setup this creates `.so` files. This is why I changed the extension above (second bullet point in this list).
- now you can run the `ppafm-gui`.

<img src="https://user-images.githubusercontent.com/1452525/233412905-ced157dc-aea5-400e-97d7-5ac941ce8522.png" width="600" />

**Comment by NikoOinonen** [comment]
> change oclUntils.py:26 to account for spaces in the path:
program = cl.Program(self.ctx, fstr ).build(options=['-I', '"' + self.CL_PATH + '"'])

That's definitely a bug. Thanks for pointing it out.

@alexriss Did you try compiling it with the Visual Studio compiler (https://github.com/Probe-Particle/ppafm#building-the-code)? When I tried with `mingw` before, I never got it working properly, but I did get it to compile with the Visual Studio compiler after some modifications. But that's a case of "well, it works on my computer", so in the end I'm not sure which way is the best.

Eventually the goal is to have automated builds for all of the platforms (#106), so maybe wait on that PR until there is some clarity on how that is going to work.

**Comment by lycheehoo** [comment]
Hi Alex,thank you so much for your detailed construction! Everything went smoothly until I ran `ppafm-gui`, errors came as below:

> D:\Anaconda3\Lib\site-packages\ppafm\cpp>ppafm-gui
>  PACKAGE_PATH =  D:\Anaconda3\Lib\site-packages\ppafm
>  CPP_PATH     =  D:\Anaconda3\Lib\site-packages\ppafm\cpp
> Traceback (most recent call last):
>   File "D:\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "D:\Anaconda3\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "D:\Anaconda3\Scripts\ppafm-gui.exe\__main__.py", line 4, in <module>
>   File "D:\Anaconda3\lib\site-packages\ppafm\cli\gui\ppafm_gui.py", line 20, in <module>
>     import ppafm.GridUtils as GU
>   File "D:\Anaconda3\lib\site-packages\ppafm\GridUtils.py", line 17, in <module>
>     lib = cpp_utils.get_cdll('GU')
>   File "D:\Anaconda3\lib\site-packages\ppafm\cpp_utils.py", line 56, in get_cdll
>     return ctypes.CDLL(str(module_path), winmode=0) # Changing to str is required on Windows
>   File "D:\Anaconda3\lib\ctypes\__init__.py", line 382, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: [WinError 193] %1  is not a valid win32 application.

I check my python eddition and the `whl` file, and tried to find solution, but I really do not know what is the matter,regrettably.

> ppafm-0.2.0a1-cp39-cp39-win_amd64.whl

> D:\Anaconda3\Lib\site-packages\ppafm\cpp>python
> Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

**Comment by alexriss** [comment]
@NikoOinonen It was mingw. The error I got was about the M_PI - that is why I uncommented the respective line. Also, I found that it is necessary to set `winmode=0` when loading the lib from python, otherwise I got the [same error as above](https://github.com/Probe-Particle/ppafm/issues/110#issuecomment-1484629120), even though the respective file existed. See also [here](https://stackoverflow.com/questions/59330863/cant-import-dll-module-in-python).

@lycheehoo This could be related to 32bit vs 64bit. Make sure that your command prompt (use powershell), your python version (this seems ok), as well as your compiler (you might have some Visual Studio compiler version that was invoked) are all 64bit. As an alternative, you can try my compiled files: [cpp_so.zip](https://github.com/Probe-Particle/ppafm/files/11295280/cpp_so.zip). Copy them into `<python-dir>\Lib\site-packages\ppafm\cpp`.

**Comment by NikoOinonen** [comment]
@alexriss I got that you used mingw. I was just curious if there is some reason that you used mingw instead of the Visual Studio compiler.

That `M_PI` constant is a bit weird. On Linux with GCC, it and other math constants are defined by default in `math.h`, with Visual Studio it's not, but you can add it with the line above: https://github.com/Probe-Particle/ppafm/blob/a1cab44c85d1cd0267592564b1ba0d343cd41bf0/ppafm/cpp/fastmath_light.h#L5 I guess on mingw neither works and you have to define it manually.

**Comment by alexriss** [comment]
The reason was that it was easier to install - using choco. And I thought it is more lightweight - but not sure if it is true :)

**Comment by NikoOinonen** [comment]
@lycheehoo If you are still trying to install ppafm on Windows, there are now pre-built wheels available, so the installation should work with just
```bash
pip install ppafm
```

**Comment by lycheehoo** [comment]
> @lycheehoo If you are still trying to install ppafm on Windows, there are now pre-built wheels available, so the installation should work with just
> 
> ```shell
> pip install ppafm
> ```

Thank you so much, Niko!

**Comment by NikoOinonen** [comment]
Everything seems fine here, so I'll close the issue.
