### ISSUE TITLE
Delete dev folder from root directory

### ISSUE THREAD

**Issue by yakutovicha** [Probe-Particle/ppafm#119]
- [x] #120
- [x] Make a new `prokop-development` branch from `main`.
- [x] Delete the `dev` folder from the `main` branch.

**Comment by ProkopHapala** [comment]
@yakutovicha ... I think these files are yours (for fitting PPAFM on DFT reference)
 ... shuld I also delete them form `main` branch and add them to the `prokop-dev` branch ? 
https://github.com/Probe-Particle/ppafm/blob/main/dev/fitPPM/plotZ.py
https://github.com/Probe-Particle/ppafm/blob/main/dev/fitPPM/fitting.py

**Comment by ProkopHapala** [comment]
@yakutovicha @NikoOinonen 
this file also does not seem mine (uses ASE for I/O)
https://github.com/Probe-Particle/ppafm/blob/prokop-dev/dev/test_io.py

**Comment by NikoOinonen** [comment]
> this file also does not seem mine (uses ASE for I/O) https://github.com/Probe-Particle/ppafm/blob/prokop-dev/dev/test_io.py

@ProkopHapala I added this while testing that the xyz IO functions work with the ASE formatted xyz files. It should be moved to the `tests` folder.

**Comment by ProkopHapala** [comment]
I forgot to backup and delete files from here, 
https://github.com/Probe-Particle/ppafm/tree/main/ppafm/dev
I will do that in next pull request after we resolve the question if  "clean_dev -> main" should be reverted or not

**Comment by NikoOinonen** [comment]
This was closed a bit prematurely. There is still one folder, `fitPPM`, inside the `dev` folder.

**Comment by ProkopHapala** [comment]
> This was closed a bit prematurely. There is still one folder, `fitPPM`, inside the `dev` folder.

Yes, that s up to @yakutovicha

**Comment by yakutovicha** [comment]
Addressing this in #152
