### ISSUE TITLE
Better explanations for all of the keywords

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#134]
We have many different keywords that can be specified in the `params.ini` file. The documentation for these is very scattered at the moment (or not existing for some), and right now it's just telling the user to look at the dictionary in the source file: https://github.com/Probe-Particle/ppafm/wiki#running-calculations. I think we would benefit from having a clear table of all of the keywords with explanations for what they do in the wiki. 

ToDo:

- [x] Move the description of parameters into tables (@yakutovicha)
- [x] Add KPFM stuff (@aureliojgc)
- [x] Pre-final look (@ondrejkrejci)
- [ ] Final look and close the issue (@ProkopHapala)

**Comment by ProkopHapala** [comment]
Sketched something on this wiki page:
https://github.com/Probe-Particle/ppafm/wiki/Params


NOTE there are some parameters which I don't know what they mean and if they are usefull anyhow. I was searching for them in the code using `vscode` and I did not find they are used. Most notably these

```
'FFgrid0':     np.array( [ -1.0, -1.0, -1.0 ] ),                # [A] ?????? does not seem to be used anywhere
'FFgridA':     np.array( [ -1.0, -1.0, -1.0 ] ),                # [A] ?????? does not seem to be used anywhere  
'FFgridB':     np.array( [ -1.0, -1.0, -1.0 ] ),                # [A] ?????? does not seem to be used anywhere
'FFgridC':     np.array( [ -1.0, -1.0, -1.0 ] ),                # [A] ?????? does not seem to be used anywhere 
'moleculeShift':  np.array( [  0.0,      0.0,    0.0 ] ),       # [A] ?????? does not seem to be used anywhere 
```
@ondrejkrejci  - is this made by you ? 


```
'tip_base':  np.array( ['None', 0.00 ]),                       # ???? perhaps not used, probably some additional poential form tip on which  probe-particle is anchored              
'Rtip'         :  30.0,                                        # ???? perhaps not used Rtip 
'permit'       :  0.00552634959,                               # ???? Permitivity? This is certainly from Aurelio/KPFM ?
'Vrange':   0.0,                                               # ???? Randge of voltage - seems to be from Aurelio/KPFM ? or STM ? 
```
These seem to be related to KPFM, or to STM, @aureliojgc , @ondrejkrejci , do you know something about these?

* NOTE: I have feeling that KPFM stuff from Aurelio is missing in the main branch ? @aureliojgc

**Comment by NikoOinonen** [comment]
The `FFgrid{0,A,B,C}` parameters are something that I added recently when implementing the parameter saving/loading for the GUI: #139. I needed some way of saving the force-field lvec separately from the sample lvec because they can be different in the `AFMulator`. These probably don't need to be documented on the same level as the other keywords, but maybe add there a notice that these can appear when saving the parameters from the GUI.

**Comment by ondrejkrejci** [comment]
'`tip_base':  np.array( ['None', 0.00 ]),                       #`
Yes that is by me. This is for the double electrostatics, which I wanted to put back to the code, as it is not there in the current form. 
`np.array` is not necessary. Any array-like is enough. The first think is string "None", "s", "pz", or "dz2". The second is a charge for "s" or charge of dipole for "pz" (dip.mom = charge x sigma) or charge of quadrupole for "dz2" (quad.mom = charge x sigma x sigma). Once it is not "None" it should start the whole second electrostatic (not in current form). 
Some explanation is here https://github.com/Probe-Particle/ppafm/wiki#note-on-parameters-in-paramsin-and-double-electrostatics

**Comment by aureliojgc** [comment]
Hi!
'Rtip'         :  30.0 is the radius of the metallic tip to calculate de cuadratic term of KPFM as if it was a capacitor form by a plane and a sphere.
permitivity is mine yes 
Vrange I am pretty sure is mine, I will dig a bit to make sure and will confirm it.

I will check the main branch to see all I added or wanted to ad is there. There is a few experimental things from my lets say "draft version" that I did not add because I wanted to clean and test before but the basic stuff from KPFM should be there.
What is it that you're missing?

 Best,
A. =)

**Comment by yakutovicha** [comment]
As soon as the [following page](https://github.com/Probe-Particle/ppafm/wiki/Params) is complete, we can close the issue:

**Comment by yakutovicha** [comment]
@aureliojgc, @ondrejkrejci, @ProkopHapala 

I put most of the information from the [wiki page](https://github.com/Probe-Particle/ppafm/wiki/Params) into a table, and now it is looking quite good. In the comment at the top I collected tasks for us, please do your part and check the box once your part is done. Then ping the following person so he can take it over.

Don't spend too much time, the document is live, so we can always update it more in the future.

@aureliojgc it is your turn now.

**Comment by aureliojgc** [comment]
I added a bit of a description on the KPFM stuff. 
tip_base is not mine as long as I remember and based on a quick grep in the ppafm directory is not used. 

@ondrejkrejci I think the ball is in your court now.

**Comment by yakutovicha** [comment]
@ondrejkrejci would you be able to work on it before our next meeting?

**Comment by yakutovicha** [comment]
@ProkopHapala, can you maybe just do the final review? I am not sure that @ondrejkrejci will work on it before the meeting.

I assume this is a very easy and quick check.

Thanks

**Comment by ProkopHapala** [comment]
Still not clear what are these.

FFgrid0 | [ -1.0, -1.0, -1.0 ] | np.array(float) | Angstrom | ?????? does not seem to be used anywhere
FFgridA | [ -1.0, -1.0, -1.0 ] | np.array(float) | Angstrom | ?????? does not seem to be used anywhere
FFgridB | [ -1.0, -1.0, -1.0 ] | np.array(float) | Angstrom | ?????? does not seem to be used anywhere
FFgridC | [ -1.0, -1.0, -1.0 ] | np.array(float) | Angstrom | ?????? does not seem to be used anywhere
moleculeShift | [0.0, 0.0,0.0 ] | np.array(float) | Angstrom | ?????? does not seem to be used anywhere

 perhaps we should try remove them and see if something breaks ?

**Comment by NikoOinonen** [comment]
> FFgrid0 | [ -1.0, -1.0, -1.0 ] | np.array(float) | Angstrom | ?????? does not seem to be used anywhere
FFgridA | [ -1.0, -1.0, -1.0 ] | np.array(float) | Angstrom | ?????? does not seem to be used anywhere
FFgridB | [ -1.0, -1.0, -1.0 ] | np.array(float) | Angstrom | ?????? does not seem to be used anywhere
FFgridC | [ -1.0, -1.0, -1.0 ] | np.array(float) | Angstrom | ?????? does not seem to be used anywhere
perhaps we should try remove them and see if something breaks ?

@ProkopHapala No, please don't remove them. As I said above, they are for compatibility between the OCL code and the params.ini specification of the CPU code:
> The FFgrid{0,A,B,C} parameters are something that I added recently when implementing the parameter saving/loading for the GUI: https://github.com/Probe-Particle/ppafm/pull/139. I needed some way of saving the force-field lvec separately from the sample lvec because they can be different in the AFMulator. These probably don't need to be documented on the same level as the other keywords, but maybe add there a notice that these can appear when saving the parameters from the GUI.


> moleculeShift | [0.0, 0.0,0.0 ] | np.array(float) | Angstrom | ?????? does not seem to be used anywhere

This one I don't know about.

**Comment by yakutovicha** [comment]
> @ProkopHapala No, please don't remove them. As I said above, they are for compatibility between the OCL code and the params.ini specification of the CPU code:

@NikoOinonen, could you please update the table with this information? https://github.com/Probe-Particle/ppafm/wiki/Params

**Comment by ondrejkrejci** [comment]
I have went through. Added some more explanation, when I thought that it would be good. 

> moleculeShift | [0.0, 0.0,0.0 ] | np.array(float) | Angstrom | ?????? does not seem to be used anywhere

My guess is that is some relict from the online version of PPAFM, as it seems not te be used, it is temporarily moved to the final sub-section: Temporary or past parameters. These can be basically removed. At the moment.

**Comment by NikoOinonen** [comment]
Did some updates:
- Changed the page name to "Setting simulation parameters" to be more descriptive: https://github.com/Probe-Particle/ppafm/wiki/Setting-simulation-parameters
- Added a description for the `FFgrid{0,A,B,C}` parameters.
- Changed `np.array(type) -> list(type)` and `float -> real` and added a list explaining the types to the beginning. I believe this is more understandable for someone not familial with Python/Numpy/programming in general.

I think the page looks good now. This issue is probably done now?

**Comment by yakutovicha** [comment]
> I think the page looks good now. This issue is probably done now?

Let's ask @ProkopHapala to do the final look and then close. Prokop, can you do that?

**Comment by ondrejkrejci** [comment]
@ProkopHapala went through, it seems to OK for now.
