### ISSUE TITLE
Proper handling of negative values in FDBM electron densities in OpenCL

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#136]
The full-density based model (FDBM) in OpenCL was implemented in #130. @ProkopHapala pointed out that there is a potential problem with negative values in the electron densities disappearing when rising them to a power and thereby changing the total charge amount in the box. The charge values should be rescaled before exponentiation like it is done in the CPU code at https://github.com/Probe-Particle/ppafm/blob/710d046686a2e9f0109556edc681db032f8f4131/ppafm/cli/conv_rho.py#L21-L24

There should probably be one OpenCL kernel that does a double sum reduction over the whole array, one for all of the values, and one for positive values, to come up with the scaling constant, and then apply that scaling in the kernel that does the exponentiation.

**Comment by ProkopHapala** [comment]
> This is more challenging to implement in a single kernel, since you would have to do two sums over the whole array. I think I will just open another issue for this.

yes, parallel reduction is a topic of itself (I'm also trying to avoid it) 

does not `Reikna` have some reduction kernell already ?

https://reikna.publicfields.net/en/latest/introduction.html#transformations 

?

**Comment by NikoOinonen** [comment]
Ah, good catch, I will take a look at it at some point.

**Comment by NikoOinonen** [comment]
In the end I didn't use reikna. Basic sum reduction is not too complicated, and I kind of wanted to learn more about it anyway. There are some good resources for it: 
https://sodocumentation.net/cuda/topic/6566/parallel-reduction--e-g--how-to-sum-an-array-
https://developer.download.nvidia.com/assets/cuda/files/reduction.pdf
Those are for cuda, but the principle is still the same.
