### ISSUE TITLE
Tip electron density resampling in FDBM in OpenCL

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#138]
The AFMulator interface to the OpenCL code by default resamples the Hartree potential grid to the chosen force field grid in order to minimize the required computations and memory (getting rid of large vacuum, etc.). However, the full-density based model implemented in #130 does not support this yet and throws an error if all of the grid sizes don't match exactly. Resampling for the tip electron density is more tricky, because the grid needs to be cropped/padded in the middle to match the physical size of the force field grid in addition to interpolation.

**Comment by ProkopHapala** [comment]
> cropped/padded in the middle to

Not sure I understand

**Comment by NikoOinonen** [comment]
When we do the convolution integral, the two grids (sample density/potential and tip density) have to match one-to-one in both their physical extent and their number of grid points in all dimensions. However, the tip density looks something like this:
<img src="https://user-images.githubusercontent.com/42408893/230097413-d41b2b93-2b72-4ac5-a443-6533b4faa525.png" alt="image" width="400"/>
The tip is centered on the corner of the box, so any operations to change the physical size of the box have to happen in the middle, so that it does not mess with the region where the density is high. Of course, you could roll the values first to the middle, pad/crop the box on the edges, and the roll it back to the corner, but that would probably be much more expensive to do.
