### ISSUE TITLE
Differences in probe relaxation between the C++ and OpenCL code

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#142]
I was noticing that the scans look slightly different between the C++ and OpenCL versions of the code. I thought before that this is just a difference from using some faster approximations for the force field calculation in the OpenCL version, but the difference is also there when the force fields are not any different.

I did some testing with the graphene example where I loaded the force field calculated by the regular run script into the OpenCL force field buffer and then doing just the relaxation on the GPU. I get images that look something like this:
![df_comp](https://user-images.githubusercontent.com/42408893/231163824-c1de9b73-9f71-4cb8-a4b5-bd2d03504b59.png)
They look very close, but not identical.

I noticed that the default time step parameters are different. In the C++ code it's hard-coded to `0.1` here: https://github.com/Probe-Particle/ppafm/blob/47cb4684bdbf6fab907109d3240764a62fe5ecaa/ppafm/cpp/ProbeParticle.cpp#L72
whereas in the OpenCL code it's set to `0.5` here: https://github.com/Probe-Particle/ppafm/blob/47cb4684bdbf6fab907109d3240764a62fe5ecaa/ppafm/ocl/AFMulator.py#L65

I tried changing the time step in the OpenCL to test if it would converge to the C++ result. This is the result for a line scan over the horizontal direction in the middle:
![df](https://user-images.githubusercontent.com/42408893/231165356-c7508411-019f-4c6b-87d8-8a70b12fd808.png)
Far from converging, there is actually a significant jump when the time step is the same `0.1`. There might also be some different prefactor, since the C++ values are consistently smaller.

@ProkopHapala Do you know if there is some other difference in the relaxation algorithms between the two versions the way you implemented them? I don't expect them to return the exact same answer, but it would be nice to know where the difference comes from.

**Comment by NikoOinonen** [comment]
The script that produces those plots is this:
```python
#!/usr/bin/env python3

import time
import numpy as np
import pyopencl as cl
import matplotlib.pyplot as plt

import ppafm.ocl.oclUtils  as oclu
from ppafm.ocl.AFMulator import AFMulator
from ppafm import PPPlot, io

q = -0.05
afmulator = AFMulator(
    scan_dim=(201, 201, 80),
    scan_window=((0, 0, 6), (20, 20, 14)),
    rho={'s': q},
    tipR0=[0, 0, 4],
    tipStiffness=[0.5, 0.5, 0.0, 20.0],
    npbc=(1, 1, 1),
    df_steps=20
)

xyzs, Zs, qs, _ = io.loadXYZ('Gr6x6N3hole.xyz')

Fx, lvec_, _, _ = io.loadXSF('FFLJ_x.xsf', xyz_order=True)
Fy, lvec, _, _ = io.loadXSF('FFLJ_y.xsf', xyz_order=True)
Fz, lvec, _, _ = io.loadXSF('FFLJ_z.xsf', xyz_order=True)
FFLJ = np.zeros((4,) + Fx.shape, dtype=np.float32, order='F')
FFLJ[0] = Fx
FFLJ[1] = Fy
FFLJ[2] = Fz

Fx, lvec_, _, _ = io.loadXSF('FFel_x.xsf', xyz_order=True)
Fy, lvec, _, _ = io.loadXSF('FFel_y.xsf', xyz_order=True)
Fz, lvec, _, _ = io.loadXSF('FFel_z.xsf', xyz_order=True)
FFel = np.zeros((4,) + Fx.shape, dtype=np.float32, order='F')
FFel[0] = Fx
FFel[1] = Fy
FFel[2] = Fz

FF = FFLJ + q * FFel

afmulator.setLvec(lvec, pixPerAngstrome=10)
afmulator.forcefield.cl_FE = cl.Buffer(afmulator.forcefield.ctx, cl.mem_flags.READ_ONLY | cl.mem_flags.COPY_HOST_PTR, hostbuf=FF)
afmulator.prepareScanner()

df_cpp, _, _, _ = io.loadXSF('Q-0.05K0.50/Amp2.00/df.xsf')

y, z = 100, 50
for dt in np.linspace(0.1, 0.5, 5, endpoint=True):
    afmulator.scanner.relax_params = np.array([dt, 0.1, 0.1*0.2,0.1*5.0], dtype=np.float32)
    t0 = time.perf_counter()
    X = afmulator.evalAFM()
    print(f'Time taken (dt = {dt:.2f}): {time.perf_counter() - t0}')
    plt.plot(X[:, y, z], label=f'dt={dt:.2f}')
    # afmulator.plot_images(X, outdir=f'afm_ocl_dt{dt:.2f}')

plt.plot(df_cpp[-z-1, y, :], 'r', label='C++')

plt.ylabel('df')
plt.xlabel('x (Å)')
plt.legend(loc='upper left')
plt.savefig('df.png')
plt.close()

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
ax1.imshow(X[:, :, z].T, cmap='gray')
ax2.imshow(df_cpp[-z-1], cmap='gray')
ax1.set_title('OpenCL')
ax2.set_title('C++')
plt.savefig('df_comp.png')
plt.close()

# FF = afmulator.forcefield.downloadFF()
# io.saveXSF('FF_test_z.xsf', FF[..., 2].T, lvec)

```

**Comment by ProkopHapala** [comment]
@NikoOinonen it is great that you do this systematic testing. In principle I think the FIRE relaxation algorithms should be the same, I don't remember I would intentionaly modify it for GPU, but the not sure I would have to look at it in detail.

I see you are comparing `df` which depend on the choice of Convolution mask in Giessible formula, there are some prefactors which may have changed over time. Maybe it would be good to compare the force `Fz` rather than `df` so that you can eliminate one unknown. (Sure if the difference is really due to convolution mask, we shooud make it consistent).

**Comment by ProkopHapala** [comment]
What about the other parameters? Especially 1) convergence criterium , 2) maximum number of relaation steps

On CPU I see this ( not sure if we modify these settings when we run the simulation ) 
```
def setRelax( maxIters  = 1000, convF2 = 1.0e-4, dt = 0.1, damping = 0.1 ):
    lib.setRelax( maxIters, convF*convF, dt, damping )
```
... btw is seems there is an error should be `convF=1e-4` not `convF2 = 1.0e-4`

On GPU I see this
```
#define N_RELAX_STEP_MAX  128
#define F2CONV  1e-8f
```

**Comment by ProkopHapala** [comment]
The algorithm put side-by-side seems exactly the same

CPU/C++ side
```C++
    inline void move( const Vec3d& f, Vec3d& r, Vec3d& v ){
        double ff = f.norm2();
        double vv = v.norm2();
        double vf = f.dot(v);
        if( vf < 0 ){ // if velocity along direction of force
            v.set( 0.0 );
            dt    = dt * fdec;
              acoef = acoef0;
        }else{       // if velocity against direction of force
            double cf  =     acoef * sqrt(vv/ff);
            double cv  = 1 - acoef;
            v.mul    ( cv );
            v.add_mul( f, cf );	// v = cV * v  + cF * F
            dt     = fmin( dt * finc, dtmax );
            acoef  = acoef * falpha;
        }
        // normal leap-frog times step
        v.add_mul( f , dt );
        r.add_mul( v , dt );
    }
```

GPU/OpenCL side:

```C++
    float ff = dot(f,f);
    float vv = dot(v,v);
    float vf = dot(v,f);
    if( vf < 0 ){ // if velocity along direction of force
        v      *= 0;
        (*dt)   = fmax( dtmin, (*dt) * FTDEC );
        (*damp) = damp0;
    }else{       // if velocity against direction of force
        // v = cV * v  + cF * F
        v       *= (1 - (*damp));
        v       +=  f * ( (*damp) * sqrt( vv / (ff + F2SAFE ) ) );
        (*dt)    = fmin( dtmax, (*dt) * FTINC );
        (*damp) *= FDAMP;
    }
    return v;
```

**Comment by NikoOinonen** [comment]
The maximum steps was important. If I set it to 1000 also on the OpenCL side, then there is no difference in the time step:
![df](https://user-images.githubusercontent.com/42408893/231370017-7f86ad83-bd57-4ab2-a5e6-1a2b771f8979.png)
But there is still a difference to the C++ result. I will try looking at the `Fz` force next.

Also interestingly, the execution time increases significantly even for the long time step when I increase the maximum number of steps, which would indicate that it does not actually ever converge within the criterion. The solution is the same by eye though, so the converge criterion might unnecessarily tight.

**Comment by NikoOinonen** [comment]
The `Fz` curve shows a similar difference:
![Fz](https://user-images.githubusercontent.com/42408893/231376976-bd03f23d-3d24-4699-9580-3b4f425a62f6.png)
But now when I'm looking at it, it looks like the C++ curve maybe has the peaks and valleys a little bit offset to the left. I'm now doubting whether the two grids are actually aligned.

**Comment by NikoOinonen** [comment]
I think I figured it out. The problem was with the coordinate transform in the force field interpolation in the OpenCL code. I actually ran into this thing before while figuring out how to interpolate the Hartree potentials etc. into a new grid. Thing is that this built-in function in OpenCL `read_imagef` seems to use a convention where the voxel coordinates are offset by half a grid step in each dimension, so the force was being calculated in the wrong spot. I modified the interpolation function like this:
```opencl
float4 interpFE( float3 pos, float3 dinvA, float3 dinvB, float3 dinvC, __read_only image3d_t imgIn ){
    float4 offset = (float4)(
        0.5f / (float) get_image_width(imgIn),
        0.5f / (float) get_image_height(imgIn),
        0.5f / (float) get_image_depth(imgIn),
        0.0f
    );
    const float4 coord = (float4)( dot(pos,dinvA),dot(pos,dinvB),dot(pos,dinvC), 0.0f ) + offset;
    return read_imagef( imgIn, sampler_1, coord );
}
```
Now it seems to return the same answer as the C++ code:
![df](https://user-images.githubusercontent.com/42408893/231421228-400b620f-195f-43ef-939b-d80a234ea43a.png)

And the scans look more-or-less identical as well:
![df_comp](https://user-images.githubusercontent.com/42408893/231421736-43e87574-0d31-4092-b1cd-4ffa03818f6b.png)
There's a couple of outlier pixels over the sharp lines, but that's probably some random numerical noise.

**Comment by ProkopHapala** [comment]
> seems to use a convention where the voxel coordinates are offset by half a grid step in each dimension
yes, I also figured this out at some point (then forgot), it is implemented in my other  project, but I fogort to update it here

```
    #if 0
        coord +=(float3){0.5f,0.5f,0.5f,0.0f}; // shift 0.5 voxel when using native texture interpolation
        const float4 fe_Paul = read_imagef( FE_Paul, sampler_gff, coord );
```

https://github.com/ProkopHapala/FireCore/blob/3df8cd1755bc59b91ec29b73217f65aadba379e1/cpp/common_resources/cl/relax.cl#L1179

But I wonder that you get so precise results using just GPU native hardware interpolation. I think when I was testing the error was quite large  `~1-4%`, that is why I made also the software interpolator `read_imagef_trilin()`

https://stackoverflow.com/questions/52261669/numerical-precision-of-linear-3d-texture-interpolation-on-gpu-opencl

**Comment by NikoOinonen** [comment]
I don't think it even is that precise. If you take the difference of the curves between the GPU and CPU computed values, you see that the maximum difference is in that range of ~1%:
![df_diff](https://user-images.githubusercontent.com/42408893/231453006-37a790b4-53c1-4dcb-a172-8ac83773f3d1.png)
Might also depend on the specific device.

Actually I also implemented a trilinear interpolator before to use in the force field calculation because of the accuracy issue as well as I needed it to work with buffer datatype instead of the image datatype: https://github.com/Probe-Particle/ppafm/blob/47cb4684bdbf6fab907109d3240764a62fe5ecaa/ppafm/ocl/cl/FF.cl#L25-L28

**Comment by ProkopHapala** [comment]
This is an other topic, but I think it would be nice to try cubic interpolation. On one hand it would require 64 (4x4x4) reads from memory, but the advantage is that it would not need to save forces (smooth forces can be calculated analytically from the cubic spline), therefore the arrays would be smaller, and probably less dense sampling would be sufficient. 

Maybe the cost of global memory read can be reduced if we read together all the values which are in the same cashe-line. Using buffer it would look something like this:

```
int yz = nx*(ix+ny*iz);
float4 vals = (float4){ grid[ix+yz], grid[ix+1+yz],grid[ix+2+yz],grid[ix+3+yz] };
```

but I'm not sure if it is really better to use buffer rather than image, because I have feeling texture reads are faster than buffer reads.

I was asking about this topic on stackoverflow, but did not get any uselful answer yet.
https://stackoverflow.com/questions/75966359/efficient-tricubic-interpolation-of-3d-image-on-gpu-using-opencl
