### ISSUE TITLE
Inconsistent parameter loading from script arguments

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#148]
I noticed recently that the z tip coordinate that is reported on the plotted images was for some reason offset by 0.5Å on the graphene example compared to what I was expecting it to be based on what I did in the OpenCL implementation. I looked into this more closely, and I think the issue is with the parameter loading from the plot script arguments.

The z distance is calculated by adding half of the amplitude to the scan z coordinate at: https://github.com/Probe-Particle/ppafm/blob/8763be1e7e851cb47a1294d49eb04fcd1c14b34b/ppafm/cli/plot_results.py#L239-L242 Notice that it uses the value from the params dict `PPU.params['Amplitude']`. These values are parsed from the command line arguments in the `apply_options` function, but it only accepts keywords that are already in the params dict: https://github.com/Probe-Particle/ppafm/blob/8763be1e7e851cb47a1294d49eb04fcd1c14b34b/ppafm/common.py#L228-L230

However, the command line argument for the amplitude is just `a`: https://github.com/Probe-Particle/ppafm/blob/8763be1e7e851cb47a1294d49eb04fcd1c14b34b/ppafm/cli/plot_results.py#L29 which does not match the value existing in the params dict: https://github.com/Probe-Particle/ppafm/blob/8763be1e7e851cb47a1294d49eb04fcd1c14b34b/ppafm/common.py#L48 so it never gets updated and it uses the default value which is different from the value supplied from the command line.

There are some other command line arguments that have the same issue. It would probably be beneficial to make some kind of dictionary of common command line arguments to use in the scripts to make sure that the names always match.

@ProkopHapala @ondrejkrejci @yakutovicha

**Comment by ondrejkrejci** [comment]
Hi, yeah this is a long way problem, how to define height when the tip is effectivery osscilating. It is the closest poin (I have used that in some paper, but always mentioned explicitely)? Is it the center of the oscillation? To be honest, I am not sure, if there is a standard in the field. Basically we should discuss, choose one of these and use them all around - in the papers, all parts and types of the code.

**Comment by NikoOinonen** [comment]
I'm fine with the current convention where it's the half-point of the oscillation. If that should be changed, then I think that's another topic. The issue that I wanted to address here is the problem with the parsing of the command line arguments into the parameter dict.

**Comment by yakutovicha** [comment]
@mondracek wanted to have a closer look at this issue and share some ideas.

**Comment by ondrejkrejci** [comment]
It would be a good to have a common dictionary for params.ini keywords and parser (longname) options with the error message as well.

**Comment by NikoOinonen** [comment]
Another thing that came to mind about the FF generating scripts, is that they all take an input file as a mandatory argument. Currently the input file is given with the `-i` option, but since it's mandatory, it would probably make more sense to make it a positional argument (no --option). But this would be a backwards incompatible change, so I'm not sure if it's worth it.

**Comment by ProkopHapala** [comment]
> Another thing that came to mind about the FF generating scripts, is that they all take an input file as a mandatory argument. Currently the input file is given with the `-i` option, but since it's mandatory, it would probably make more sense to make it a positional argument (no --option). But this would be a backwards incompatible change, so I'm not sure if it's worth it.

I don't think it is good idea, I never remember the order of positional argumens and typically I prefer to use named auguments even in function calls. (Actually this is one think I like more about python over C++)
