### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#176]
Directed mostly towards @yakutovicha, but other could probably chime in as well (@ondrejkrejci, @ProkopHapala, @mondracek).

So we setup the PyPI release system (#170) (,although there as still some issues #173), and we have `bumpver` (#171) to make the release process easy. But when do we make a new release? Currently we have an alpha release `0.2.0a3` and we have incremented the alpha tag a couple of times.
* Should we make a new alpha release for every merge to the main, or just when we feel like it?
* When do we make a stable release and increment the patch version?
* When do we increment the minor release?

On a related note. I think we should make a stable release on PyPI soon, because we now have the pip installation instructions right at the top of the README, but the current stable release on PyPI is very outdated. I don't see any reason to delay, considering that the current alpha version is probably more stable than the current "stable" release.

**Comment by yakutovicha** [comment]
We follow the semantic versioning scheme. Everything is described [here](https://semver.org/) - very clearly and concisely.

I learned that if the leading number is 0 (e.g. 0.1.2, 0.5.1), it is ok to do API changes. The project is considered in a development state.

Concerning pre-releases: alpha means the new API is not stable, and beta means the API is stable, but bugs are still expected.

is that OK with everybody?

**Comment by yakutovicha** [comment]
> * Should we make a new alpha release for every merge to the main, or just when we feel like it?

This is probably still unanswered in the previous message. I do not think the semantic versioning poses any constraints on the timing. I think "when we feel like it" is probably the right approach.

**Comment by NikoOinonen** [comment]
> We follow the semantic versioning scheme. Everything is described [here](https://semver.org/) - very clearly and concisely.

Ok, great, I see that the link is on the developer wiki page as well.

> Concerning pre-releases: alpha means the new API is not stable, and beta means the API is stable, but bugs are still expected.
> I do not think the semantic versioning poses any constraints on the timing. I think "when we feel like it" is probably the right approach.

This is good for the long run, but I think at the moment we don't really have any plan on what the public API should be exactly, so it's not clear when it would be considered stable. I repeat that I think we should make a stable release with the current alpha version, just so that when people try and install with `pip install ppafm` like it says on the README, they actually get a functioning version of the code. If I recall, the current stable `0.1.0` version doesn't install the command-line scripts, so all of the examples are broken, for example.

**Comment by NikoOinonen** [comment]
I could do it, just to try it out.

**Comment by NikoOinonen** [comment]
Ok, it's done: https://github.com/Probe-Particle/ppafm/releases/tag/v0.2.0. It really was easy.
