### ISSUE TITLE
About CI and tests on the wiki

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#184]
There has still been some confusion about the CI workflows and tests in the meetings and elsewhere, so I made sections in the developer wiki page for those: https://github.com/Probe-Particle/ppafm/wiki/For-Developers#continuous-integration

Would this make it more clear, or is there something more to add?

@ondrejkrejci @mondracek @ProkopHapala @yakutovicha

**Comment by yakutovicha** [comment]
Thanks, @NikoOinonen. I made a few [minor changes](https://github.com/Probe-Particle/ppafm/wiki/For-Developers/_compare/30bd420c948f97151a70dd0f9b938d9f3d3bd490...7ee3ab12920c9c9d29ae1b7bd9906d2187d24874). As a general suggestion - please keep one sentence per line. It is handy for further edits.

**Comment by yakutovicha** [comment]
@NikoOinonen, shall we close it?

**Comment by NikoOinonen** [comment]
I guess no one has any more opinions, so we can close it.
