### ISSUE TITLE
Example of organometallic complex not working

### ISSUE THREAD

**Issue by ELpolloGUAPO** [Probe-Particle/ppafm#191]
Hello,
I have been around with the examples and am particularly interested in simulating AFM images of molecules on surfaces. The only example like this is CoPc-IETS, which unfortunately crashes when trying to run it. Here's the output that I get (error in the end):

ricardo@PC-KL-23518:/mnt/c/Users/RUVALCRM/Downloads/ppafm-main/examples/CoPc-IETS$ bash run.sh
 PACKAGE_PATH =  /home/ricardo/.local/lib/python3.10/site-packages/ppafm
 CPP_PATH     =  /home/ricardo/.local/lib/python3.10/site-packages/ppafm/cpp
>>>BEGIN: computeLJ()
[204 202 200] [20.45  0.    0.  ] [ 0.         20.24446715  0.        ] [ 0.  0. 20.]
FFLJ.shape (200, 202, 204, 3)
 nxyz  204 202 200
cell [[20.45        0.          0.        ]
 [ 0.         20.24446715  0.        ]
 [ 0.          0.         20.        ]]
 n      204 202 200
 a      20.450000 0.000000 0.000000
 b      0.000000 20.244467 0.000000
 c      0.000000 0.000000 20.000000
 da     0.100245 0.000000 0.000000
 db     0.000000 0.100220 0.000000
 dc     0.000000 0.000000 0.100000
 inv_da 9.975550 0.000000 0.000000
 inv_db 0.000000 9.978035 0.000000
 inv_dc 0.000000 0.000000 10.000000
interateGrid3D nx,y,z (204,202,200) nxy 41208
ic 199
Clamp force > 10.0
computeLJ Save  xsf
Saving xsf FFLJ_x.xsf
Saving xsf FFLJ_y.xsf
Saving xsf FFLJ_z.xsf
<<<END: computeLJ()
 PACKAGE_PATH =  /home/ricardo/.local/lib/python3.10/site-packages/ppafm
 CPP_PATH     =  /home/ricardo/.local/lib/python3.10/site-packages/ppafm/cpp
Ks   = [0.5]
Qs   = [0.0]
 ============= RUN
 load Lenard-Jones Force-field
nDim xsf (= nDim + [1,1,1] ): [201 203 205]
io | Load FFLJ_x.xsf using readNumsUpTo
FileRead program: reading FFLJ_x.xsf file
XYZ dimensions are 201 203 205
Reading DONE
io | Done
nDim xsf (= nDim + [1,1,1] ): [201 203 205]
io | Load FFLJ_y.xsf using readNumsUpTo
FileRead program: reading FFLJ_y.xsf file
XYZ dimensions are 201 203 205
Reading DONE
io | Done
nDim xsf (= nDim + [1,1,1] ): [201 203 205]
io | Load FFLJ_z.xsf using readNumsUpTo
FileRead program: reading FFLJ_z.xsf file
XYZ dimensions are 201 203 205
Reading DONE
io | Done
[[ 0.          0.          0.        ]
 [20.45        0.          0.        ]
 [ 0.         20.24446715  0.        ]
 [ 0.          0.         20.        ]]
 relaxed_scan for  Q0.00K0.50
>>>BEGIN: perform_relaxation()
 nxyz  204 202 200
cell [[20.45        0.          0.        ]
 [ 0.         20.24446715  0.        ]
 [ 0.          0.         20.        ]]
 n      204 202 200
 a      20.450000 0.000000 0.000000
 b      0.000000 20.244467 0.000000
 c      0.000000 0.000000 20.000000
 da     0.100245 0.000000 0.000000
 db     0.000000 0.100220 0.000000
 dc     0.000000 0.000000 0.100000
 inv_da 9.975550 0.000000 0.000000
 inv_db 0.000000 9.978035 0.000000
 inv_dc 0.000000 0.000000 10.000000
stiffness: [ 0.5  0.5 20. ]
 IN setTip !!!!!!!!!!!!!!
 lRadial  4.0
 kRadial  -1.248301864756392
 rPP0  [0. 0. 0.]
 kSpring  [-0.03120755 -0.03120755 -0.        ]
 rPP0 0.000000 0.000000 -4.000000
>>BEGIN: relaxedScan3D()
 zTips :  [ 9.5  9.6  9.7  9.8  9.9 10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8
 10.9 11.  11.1 11.2 11.3 11.4 11.5]
relax ix: 190<<<END: relaxedScan3D()
<<<END: perform_relaxation()
Saving xsf Q0.00K0.50/OutFz.xsf
 === computing eigenvectors of dynamical matix which=3 ddisp=0.050000
run.sh: line 4:   628 Segmentation fault      ppafm-relaxed-scan --vib 3
 PACKAGE_PATH =  /home/ricardo/.local/lib/python3.10/site-packages/ppafm
 CPP_PATH     =  /home/ricardo/.local/lib/python3.10/site-packages/ppafm/cpp
plot WITHOUT Xserver
 >> OVEWRITING SETTINGS by command line arguments
Ks   = [0.5]
Qs   = [0.0]
Amps = [1.0]
 ============= RUN
error:  (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x7ffb48f16080>)
cannot load :  Q0.00K0.50/PPpos_?.xsf
 ***** ALL DONE *****

Additionally, there are no images generated on the folder. Any advice on how to make this work?

**Comment by NikoOinonen** [comment]
The CoPc-IETS example is known to be broken (#71). There has not been very high priority on it, since it's unclear if anyone needs the IETS functionality. If you think this is important for you, then we can look into fixing it.

**Comment by ELpolloGUAPO** [comment]
Hello,
Yes please. It is my primary intention for using this program to simulate molecules on surfaces.
Interestingly enough, the online module that you guys created successfully creates the AFM images. Here's the link:
http://ppr.fzu.cz/results.php?hash=1691514812_athAsgChfA

**Comment by NikoOinonen** [comment]
@ondrejkrejci You were assigned on the other issue, so maybe you can comment on when it would be possible to fix this.

**Comment by ondrejkrejci** [comment]
Hi @ELpolloGUAPO - the CoPC example is now fully working, thanks to Prokop's help. Needless to say, that the AFM part was working all the time. I will close this issue.
Please let us know, if you run to any other problems.
