### ISSUE TITLE
Wrong height of the scanned region in df.xsf

### ISSUE THREAD

**Issue by mondracek** [Probe-Particle/ppafm#199]
The third vector delineating the (height of) the scanning region is wrong in the `df.xsf` file generated by `plot_results.py --save_df`. The origin recorded in this file is probably wrong too, though this depends on the convention we want to adopt for the _z_ position of the oscillating tip: If we use the lower turning point of the oscillating tip as its height _z_, it would be okay, but I think we should rather use the _z_ coordinate of the central point around which the tip oscillates and then the origin is wrong too. Anyway, either the scan starts at `params['scanMin'] + A/2` and finishes at `params['scanMax'] - A/2`, or it starts at `params['scanMin']` and finishes at `params['scanMax'] - A`. In any case, the height of the scanned region must be `params['scanMax'] - params['scanMax'] - A`. What happens instead is that `plot_results.py` blindly copies `lvec` from `OutFz.xsf` to `df.xsf` without subtracting the amplitude `A` from the third box-defining vector. See here https://github.com/Probe-Particle/ppafm/blob/2344a7b01000bbf8ce3d2ddbf92abf3b9fe917c9/ppafm/cli/plot_results.py#L169-L180
This issue may be related to #6 but it happens with any kind of tip, not just the complex one. The obvious way to repair it is to modify the `lvec` array by subtracting the amplitude from its appropriate element before writing `df.xsf`. We just have to be careful about the exact value of the amplitude; as I understand it, it is always rounded to an integer number of grid points.

**Comment by ondrejkrejci** [comment]
Hei Martin,

I need to warn you, that such a changes could afect the PPSTM code. Have you changed any parameters that are getting into the positions that are saved on the similar level? Because I think so.
I am totally fucked up, but I will try to look at this at some point.
Ondrej

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
