### ISSUE TITLE
ppafm.io.loadGeometry returns wrong properties with FHI-aims format input

### ISSUE THREAD

**Issue by LauriKurki** [Probe-Particle/ppafm#201]
When calculating the LJ potential with e.g. `ppafm-generate-ljff` using input in FHI-aims format, io.loadGeometry should return `atoms, nDim, lvec`. See line 149 here:
https://github.com/Probe-Particle/ppafm/blob/2344a7b01000bbf8ce3d2ddbf92abf3b9fe917c9/ppafm/HighLevel.py#L143-L149

io.loadGeometry() further calls io.loadGeometryIN(fname) which should return `atoms, nDim, lvec` but instead it returns `atoms, Zs, lvec`

https://github.com/Probe-Particle/ppafm/blob/2344a7b01000bbf8ce3d2ddbf92abf3b9fe917c9/ppafm/io.py#L117-L138

~~Should we read gridN from params.ini to get the dimensions, or assume something like a 0.1Å grid?~~

E: I see there was some previous discussion at least in #197 and #52 on how to handle the grid so it is probably not needed here. The bug with the return value is still relevant.

**Comment by NikoOinonen** [comment]
Thanks for the bug report. This should be pretty easy to fix.
