### ISSUE TITLE
The examples in examples/_bak do not work

### ISSUE THREAD

**Issue by mondracek** [Probe-Particle/ppafm#208]
The examples in `examples/_bak` seem not to be maintained. The scripts to run them do not reflect changes in the structure of the main code.

**Comment by NikoOinonen** [comment]
I think this was one of the folders @ProkopHapala said not to touch?

**Comment by ProkopHapala** [comment]
> I think this was one of the folders @ProkopHapala said not to touch?

yes, it is quite possible I said that. :) But looking on them now I have now idea what was the context anymore, and I have no intention to do anything with them in future. So If you prefer to **delete** this folder, I'm probably fine with that.

**Comment by NikoOinonen** [comment]
I would vote for deletion so that no one has to wonder in the future what they are there for.
