### ISSUE TITLE
add OpenMP acceleration?

### ISSUE THREAD

**Issue by ProkopHapala** [Probe-Particle/ppafm#224]
There is huge discrepancy between speed of GPU and CPU code (>100x), which is a bit unfair because modern multi-core vectorized CPUs are able to provide much higher performance than what we are currently using. 

Adding vectorized version of forcefield evaluation and probe-particle relaxation should be rather staightforward. Although it is a question if there is considerable motivation to do that when we have already super vast OpenCL implementation?

**Comment by ProkopHapala** [comment]
@yakutovicha @NikoOinonen 

I see something about that continuous integration has failed
https://github.com/Probe-Particle/ppafm/actions/runs/6744438095/job/18334286134

but the problem is in parts of code I did not touched (OpenCL, Reikna etc.)

[![continuous-integration](https://github.com/Probe-Particle/ppafm/actions/workflows/ci.yml/badge.svg)](https://github.com/Probe-Particle/ppafm/actions/workflows/ci.yml)

**Comment by ondrejkrejci** [comment]
@ProkopHapala Thank you! It seems to be working fine even on my crazy Windows laptop!

**Comment by mondracek** [comment]
@ProkopHapala , @ondrejkrejci : Guys, so how do you run the `ppafm` code to make it use OpenMP & more than 1 cpu?

**Comment by ProkopHapala** [comment]
I think it should do it by default as it is compiled with `-fopenmp` in [Makefile](https://github.com/Probe-Particle/ppafm/blob/main/ppafm/cpp/Makefile), 
 * Does it not? 
 * Do you have set the [OMP_NUM_THREADS](https://www.openmp.org/spec-html/5.0/openmpse50.html) evironemnt variable?
 * Note: OpenMP paralelization is used only for grid projection, and tip relaxation, it is not used for FFT, which may be the bottleneck in many cases.

**Comment by ProkopHapala** [comment]
* I typically set OMP_NUM_THREADS to number of cores -1 (I reserve one core to make sure computer is responsive when running something on desktop, on server its different storry)
* I don't know about FHI-AIMS or VASP specifically, but I guess you run them with MPI. For OpenMP OMP_NUM_THREADS is standard way how to control it, but it is true, one can override it in the code.
