### ISSUE TITLE
Fix codecov report

### ISSUE THREAD

**Issue by yakutovicha** [Probe-Particle/ppafm#241]
Currently, there are two codecov reports, one called `codecov/patch` and `codecov/project`. The first one is constantly failing, while the second one is passing.

This inconsistency should be fixed.

**Comment by mondracek** [comment]
I am not sure it is really an inconsistency. Does not the first test (`codecov/patch`) check the percentage of tested lines only within the lines that have been modified while the second (`codecov/project`) checks the percentage of tested lines among all lines in the whole `ppafm` package? If so, they are really two different tests, which can be expected to give different results. Namely, if you make only a small change, the status of the `codecov/project` test is unlikely to change, if it passes before, it probably will after a small change too, if it did not pass before, it will probably keep failing (definitely so unless you added some new tests to cover the change and likely even if you did). So I don't think it is literally a bug to be fixed if `codecov/patch` fails while `codecov/project` passes, but applying the `codecov/patch` may be a too strict criterion at this stage. Should we deactivate it?

**Comment by yakutovicha** [comment]
should be disabled now. Please reopen in case of problems
