### ISSUE TITLE
KPAFM: check that all examples working fine

### ISSUE THREAD

**Issue by yakutovicha** [Probe-Particle/ppafm#243]
We should add an example of CH3Br simulation in the examples folder and make sure it runs fine.

**Comment by mondracek** [comment]
Where can I upload the *cube or *xsf files for the examples once I have them ready? Should I make them part of the distribution, tracked by git?

**Comment by NikoOinonen** [comment]
@mondracek You could use Zenodo. I recently added an example for the main simulations figure: https://github.com/Probe-Particle/ppafm/pull/248, where I uploaded the dataset to Zenodo: https://doi.org/10.5281/zenodo.10418629. You can login with your Github account. They allow up to 50GB per upload, and you can get a DOI and a download link for the dataset.

**Comment by yakutovicha** [comment]
We agreed that @mondracek will add a CH3Br example and will do a final check. If everything works fine, he will close the issue.

**Comment by mondracek** [comment]
Now both FFPB_KPFM and CH3Br_KPFM examples work. I am creating a pull request.
