### ISSUE TITLE
Proper documentation for the FDBM (full denity based method) is missing

### ISSUE THREAD

**Issue by mondracek** [Probe-Particle/ppafm#258]
Either missing or I was not able to find it. Yes, there is at least the `ppafm/examples/pyridineDensOverlap` example and `ppafm/examples/paper_figure` can be used as another example for the GPU version, though it is rather awkward to use `ppafm/examples/paper_figure/run_simulation.py` as a template for other simulations: It is too much tuned to generate the one specific figure.

Anyway, my problems is that while I believed I was able to launch full-density based simulations using those examples as a template, once i ran into difficulties, I could never be sure whether there was a bug in the code or I just made a mistake in the way I was trying to use it.

This issue began to bother me in my attemtps to simulate a cyclodextrin molecule, in which I have arrived to issue #257. I am now pretty sure that the source of that specific problem is in the DFT-D3 part, but there may or may not be other issues in the FDBM functionality. If I am to report the problems I encounter, however, I need to know what is *supposed* to work.

**Comment by NikoOinonen** [comment]
Yes, the documentation is too sparse. I have been meaning to write proper explanations of everything, but never got around to it. There is some limited documentation of the Python API:
- https://ppafm.readthedocs.io/en/latest/ppafm.ocl.html#module-ppafm.ocl.AFMulator
- https://ppafm.readthedocs.io/en/latest/ppafm.ocl.html#ppafm.ocl.field.ForceField_LJC.calc_force_fdbm

**Comment by ondrejkrejci** [comment]
I have added the FDBM part of the literature on our Main wiki page, once somebody has a time, please put there right citations. Thank you!

**Comment by NikoOinonen** [comment]
I added there a citation to the original paper.

**Comment by NikoOinonen** [comment]
I added a new section to the [Forces](https://github.com/Probe-Particle/ppafm/wiki/Forces) wiki page about the different force field models and how to use them with the CLI. There is still no documentation on the OpenCL version, but I think it would better fit the API doc page and I intend to make those better some time soon (#264).

@ondrejkrejci @mondracek could you check out that wiki page if it makes sense or if something should be added or organized differently.

**Comment by NikoOinonen** [comment]
Also relevant to this issue, there is now a tutorial on the Python API for the OpenCL version of the code at https://ppafm.readthedocs.io/en/latest/tutorials/index.html.

**Comment by ondrejkrejci** [comment]
@NikoOinonen @mondracek - I have updated the [forces wiki](https://github.com/Probe-Particle/ppafm/wiki/Forces#force-field-models). If you recheck it quickly, I think that we can close this issue.

@NikoOinonen - great job with readthedocs, by quick reading I think that it is better explained, then in the wiki.

**Comment by NikoOinonen** [comment]
I made a couple of small adjustments to the wiki page. Everything looks good from my side.

**Comment by yakutovicha** [comment]
@mondracek will do the final check and potentially close the issue.

**Comment by mondracek** [comment]
@ondrejkrejci , @NikoOinonen , thanks for the job. I looked at the Wiki section about forces and I think it's good. I just added one sentence to the section about FDBM, emphasizing the need of the same cell geometry for the tip and the sample.

**Comment by NikoOinonen** [comment]
@mondracek 

>  I just added one sentence to the section about FDBM, emphasizing the need of the same cell geometry for the tip and the sample.

This limitation actually does not exists in the OpenCL version, because it can resample the tip cell to match whatever force-field grid you want. I haven't implemented this in the CPU version, but I could maybe do it at some point if it's something that would be useful to you.

**Comment by yakutovicha** [comment]
The documentation on this topic can be found [here](https://github.com/Probe-Particle/ppafm/wiki/Forces#full-density-based-model).
