### ISSUE TITLE
Adding a beter description for the Zenodo database of images

### ISSUE THREAD

**Issue by ondrejkrejci** [Probe-Particle/ppafm#260]
I will write something for FePc (IETS) and STM @mondracek, could you do something also for the KPFM. Who could write, how the Fig. 2 was obtained?

**Comment by ondrejkrejci** [comment]
> > how the Fig. 2 was obtained
> 
> What exactly do we want here? The description of the parameters is already in the paper, and the script is in the examples.

Just a description, what script you should run, to get the image. Thus just in the zenodo database, to say the what is the path to that script.

**Comment by ondrejkrejci** [comment]
Sure, I am overwhelmed as well, I just wanted to remind myself too 😊. Thank you!

**Comment by mondracek** [comment]
To specify, I mean I can write about the KPFM figure, not so much Fig. 2. Probably @NikoOinonen is the best person to write about Fig. 2.

**Comment by ondrejkrejci** [comment]
[heart]         Krejci Ondrej reacted to your message:
________________________________

**Comment by NikoOinonen** [comment]
> Probably @NikoOinonen is the best person to write about Fig. 2.

Yes, I can do this.

**Comment by mondracek** [comment]
@ondrejkrejci , how can I access the Zenodo database?

**Comment by ondrejkrejci** [comment]
I think that @Oinonen ***@***.***> is taking care of that. I have sent him the description of my part.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ondrejkrejci** [comment]
By the way @NikoOinonen once you will be changing the description at the (zenodo)[https://zenodo.org/records/10563098] please temporarily change the "paper" to the manuscript. We can also put there the arXiv citation: (arXiv:2401.14564)[https://arxiv.org/abs/2401.14564]. And there is also wrongly speled Angstrom, but that is a very minor issue :-) .

**Comment by NikoOinonen** [comment]
@mondracek If you can provide the KPFM description, then I can do the update.

**Comment by mondracek** [comment]
@NikoOinonen , I would follow @ondrejkrejci 's template, if you don't mind, something like this:
> The LCPD and AFM maps shown at Figure 3 (a,b) of the manuscript could be obtained with the PPSTM code (https://github.com/Probe-Particle/PPSTM). After download and installation, navigate to the examples/FFPB_KPFM/ folder and download the archive file KPFM_hartree.tar.gz (https://zenodo.org/records/10563098/files/KPFM_hartree.tar.gz?download=1) to this folder.  Expand it to get the LOCPOT_V0.xsf and LOCPOT_Vz.xsf files and then run the script ./run.sh
> After running the scipt, the LCPD map of Figure 3(a) can be found in examples/FFPB_KPFM/LCPD_atoms_cbar_018.png and the AFM map of Figure 3(b) in examples/FFPB_KPFM/Q-0.10K0.25V0.00/Amp0.50/df_atoms_cbar_018.png

**Comment by NikoOinonen** [comment]
So all together, I would put there something like this:

> Reproducing the figures in the manuscript:
> - Fig. 2 (comparison of force-field models): Install ppafm with the [opencl] option, and run the example script in the ppafm repository at examples/paper_figure/run_simulation.py. The image is saved into the same folder with the script.
> - Fig. 3 (KPFM LCPD map): Install ppafm, navigate to examples/FFPB_KPFM, and run the script ./run.sh. After running the script, the LCPD map of Fig. 3(a) can be found in LCPD_atoms_cbar_018.png and the AFM map of Fig. 3(b) in Q-0.10K0.25V0.00/Amp0.50/df_atoms_cbar_018.png.
> - Fig. 4 (STM dI/dV map): Download and compile the PPSTM code (https://github.com/Probe-Particle/PPSTM). After that navigate to tests/PTCDA_mol and use the run_all.sh script.
> - Fig. 5 (IETS): Install ppafm, navigate to examples/FePc_Au-IETS, and run the script run_ppafm-iets.sh. The IETS image can be found in the Q0.00K0.24 folder.
> 
> The ppafm version 0.3.1 was used when producing the images for the manuscript.

Are we happy with this?

@mondracek I removed the thing about downloading the data, since the run.sh script already seems to do that automatically.

@ondrejkrejci Maybe we should add also some version/commit number for the PPSTM code, to ensure reproducibility?

**Comment by ondrejkrejci** [comment]
@NikoOinonen - agreed from my side.

The PPSTM version is this one: https://doi.org/10.5281/zenodo.10669867 (it is named v1.0.2), which is an ooold mistake of mine, when I did not understand naming.

**Comment by NikoOinonen** [comment]
I updated the Zenodo description and added a reference to the arXiv preprint there: https://zenodo.org/records/10563098

**Comment by ondrejkrejci** [comment]
@NikoOinonen - thank you. I think that we can close this issue, until the paper is published.

We can update the description, based on (hopefull) publishing and maybe on referees comment.

Thank you all for working on it!
