### ISSUE TITLE
new version, of PPAFM released and added to Zenodo description 

### ISSUE THREAD

**Issue by ondrejkrejci** [Probe-Particle/ppafm#261]
after #259 .

**Comment by ondrejkrejci** [comment]
It is free to go now!

**Comment by NikoOinonen** [comment]
I just bumped up the version, should be up in a few minutes.

**Comment by NikoOinonen** [comment]
Nevermind, the build failed: #263. I'll try to fix it soon.

**Comment by NikoOinonen** [comment]
Ok, now there is a release.
