### ISSUE TITLE
Too many names

### ISSUE THREAD

**Issue by yakutovicha** [Probe-Particle/ppafm#266]
Now things are called Probe-Particle, probe particle, ppafm, pp, etc. At least for me is not always clear the context where they are supposed to be used.

Let's agree on a (maybe shorter) list of names and be very specific about what they mean.

I think this is a very important issue to fix before moving further.

## Agreement:

Probe-Particle Model (in capital letters) - the name of the simulation model/method
probe particle or PP - the simulation particle (e.g. CO or Xe)
ppafm - the name of this Python package as well as the general term for an AFM simulation done using the Probe-Particle Model.

## To be closed:

Let's close this issue when the documentation found on the [wiki](https://github.com/Probe-Particle/ppafm/wiki) is updated according to the agreed namings.

**Comment by NikoOinonen** [comment]
In my mind I understand those terms like this:
- Probe-Particle Model (in capital letters) - the name of the simulation model/method
- probe particle - the simulation particle (e.g. CO or Xe)
- pp/PP - abbreviation of probe particle
- ppafm - the name of this Python package as well as the general term for an AFM simulation done using the Probe-Particle Model.

**Comment by ProkopHapala** [comment]
@yakutovicha - where you mean these names bother you? E.g. 
1. In the source code?
2. In the documentation?
3. In the article?

Personaly I don't have any specific reason to use any of them, I just say what first came to my mind. I really hate formalities bureaucracy and all that shit. Generally when I write something have problem to keep even spelling consistent, if automatic spell checkrt does not help me.  So feel free to modify / unify the names in the docs if you feel like it is importaint for you.

**Comment by ondrejkrejci** [comment]
Hei everyone, I have renamed the things on our Wiki accordingly and added a [wiki section](https://github.com/Probe-Particle/ppafm/wiki#notes-on-the-naming) that is explaining the names.

Together with that, I have updated the README to be on the same ballpark everywhere. Let me know, what do you think guys.

**Comment by NikoOinonen** [comment]
Thanks Ondrej, everything looks good to me at least. Probably we can close this with the merge of #271?
