### ISSUE TITLE
Addressing point 1 of the reviewer.

### ISSUE THREAD

**Issue by ondrejkrejci** [Probe-Particle/ppafm#283]
The reviewer was saying this: _(1) The authors should shorten the review of the background theoies (Sec. 2 and Sec. 3) and the new features of the latest version should be highlighted, if they are contained in this paper._

In this, I would opt for what we should do about that one, to make some reasonable response.

**Comment by ondrejkrejci** [comment]
I would be more polite in our response, then it is written now in the [google doc.](https://docs.google.com/document/d/1d4GnJCrv7FVM2er8cDycUFRi-16s67tSpntroWNuoIY/edit)

I would go with a trying to remove some of parts of the [text](https://www.overleaf.com/project/64882ce9df7e620b31b01a9a), e.g. this part:
![image](https://github.com/Probe-Particle/ppafm/assets/13340693/662c9f2d-b46e-41b1-a484-4bfa31e4bafd)

**Comment by ProkopHapala** [comment]
> _new features of the latest version should be highlighted, if they are contained in this paper._

yes, I think this is actually more importaint than to shorten the review part. We should clearly say what is the new development, in the manuscript as well as in the referee response. 

I aleready added this to referee response:

> The new features implemented in PPAFM package which were not previously published include:
> 
> - Implementation of FDBM (although we did not developed the method)
> - Benchmarking the accuracy of each method with respect to DFT reference
> - GPU acceleration and OpenMP parallelization
> - interactive GUI
> - integration into pip ecosystem
>

**Comment by ondrejkrejci** [comment]
Continuation from #68 :

> Generally, with rescpet to the parts you want to remove (yellow), I would prefer to keep them as they makes the text more fluent and engaging and give some context. The KPFM without the equation would be very blank. I don't think this is what referee asks for (i.e. shorten the text because it is too long), referee was compainging that is looks like review paper, and that it was not clear what is new.

I understand your point, please let me explain mine:

- I am not saying that we need to remove everything that I am suggesting, I am open for a discussion, but I would rather do it one-by-one.
- I do not want to remove physics at all, I just want to remove some information, that is not fully necessary 
- I have already shortened a text in 3.2 and 3.3. I am never removing an important information about the model.
- I know that the referee wanted to redo 2 and remove 3 in reality, but showing that we did everything in (2-5) and we have shortened the text for (1) sounds to me still as a better solution, than saying that we did almost nothing for (1).
- The reviewer is saying that 60% of the text is review. (Even though I have found no policy on amount of new/review) if we shorten 2 and 3 (a little) and we have prolonged 5, we will be closer to 50% and it will sound better for both - the reviewer and the editor.

**Comment by ondrejkrejci** [comment]
@ProkopHapala - Ok, I have went through everything, and I have updated the response a little bit.

We have now still some time, for the response, but sooner submitted, sooner published :-) . 

Just if you are interested, except for that one KPFM part, I have applied all my suggested changes in this file:
[Probe_particle_overview-short.pdf](https://github.com/user-attachments/files/15809777/Probe_particle_overview-short.pdf)
