### ISSUE TITLE
Invalid command option in Wiki

### ISSUE THREAD

**Issue by huangchieh** [Probe-Particle/ppafm#307]
In [wiki](https://github.com/Probe-Particle/ppafm/wiki) document, 

> 1. **Calculation of Lennard-Jones and Electrostatic forcefield over sample.**
> This is done by running the script (all the ppafm scripts are explained [here](https://github.com/Probe-Particle/ppafm/wiki/Command-line-interface)):
>```
>ppafm-generate-ljff -i input.xyz -q
>```

the option `-q` seems not valid. 

```bash
> ppafm-generate-ljff -i PTCDA.xyz  -q
usage: ppafm-generate-ljff [-h] -i INPUT [-F INPUT_FORMAT] [-f OUTPUT_FORMAT] [--ffModel FFMODEL] [-E] [--noPBC]
ppafm-generate-ljff: error: unrecognized arguments: -q
```

**Comment by ondrejkrejci** [comment]
Hi @huangchieh - It was comming from older version of the code. Please have a look at the [wiki](https://github.com/Probe-Particle/ppafm/wiki), which is updated now and should be clear about it. Feel free to reopen the issue, if you still find it problematic. Thank you for spotting this!
