### ISSUE TITLE
Problems with spline interpolation code.

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#308]
While debugging the CI tests (#279) I found at least two different issues in the spline interpolation C++ code that is causing segmentation faults.

First, on this line of code, the variable `i` seems to be uninitialized, and sometimes can be some large value that causes an out of bounds access later: https://github.com/Probe-Particle/ppafm/blob/17ee88460f0614843d1740c4d6e0dacbc0a9758f/ppafm/cpp/ProbeParticle.cpp#L211 @ProkopHapala Can you check what this is supposed to be, since you wrote it.

The other issue is that once the spline parameters are set using `ppafm.core.setTipSpline`, the spline interpolation remains in effect for the whole rest of the program, because the code only checks whether the pointer exists when deciding what algorithm to use: https://github.com/Probe-Particle/ppafm/blob/17ee88460f0614843d1740c4d6e0dacbc0a9758f/ppafm/cpp/ProbeParticle.cpp#L283-L287 This leads to two problems:
1. The parameter arrays don't necessarily exist anymore (Python garbage collector?), so the pointer could be pointing to an invalid location. This seems to be happening in the current CI test setup that is randomly giving seg faults because of this.
2. If you run multiple calculations in a row, which is now possible after we rearranged all the things, you could be using the wrong algorithm without knowing, if the spline was set somewhere else. I suggest that we add a corresponding `else` block in `perform_relaxation` that explicitly sets the spline parameters to `None` when they were not specified: https://github.com/Probe-Particle/ppafm/blob/17ee88460f0614843d1740c4d6e0dacbc0a9758f/ppafm/HighLevel.py#L138

Any thoughts @ProkopHapala @ondrejkrejci @yakutovicha @mondracek?

**Comment by ProkopHapala** [comment]
Hi Niko, thanks that you look on it.

#### 1

the function `Spline_Hermite::find_index<double>( i, n-i, x, xs );` is doing binary search for index `i` 
where  `xs[i]<= x <= xs[i+1]`
so that we can do subsequent interpolation.

But the fact that argument i is uninitialized is clearly wrong. I think there should be `Spline_Hermite::find_index<double>( 0, n, x, xs )`, 

I think I blindly copied it from somewhere, where I already had some estimete of `i`. It was probably working as long as unitialized variable `i=0`.

#### 2

> The other issue is that once the spline parameters are set using `ppafm.core.setTipSpline`, the spline interpolation remains in effect for the whole rest of the program, because the code only checks whether the pointer exists when deciding what algorithm to use:
> 
> https://github.com/Probe-Particle/ppafm/blob/17ee88460f0614843d1740c4d6e0dacbc0a9758f/ppafm/cpp/ProbeParticle.cpp#L283-L287
> 
> This leads to two problems:
> 1. The parameter arrays don't necessarily exist anymore (Python garbage collector?), so the pointer could be pointing to an invalid location. This seems to be happening in the current CI test setup that is randomly giving seg faults because of this.
> 2. If you run multiple calculations in a row, which is now possible after we rearranged all the things, you could be using the wrong algorithm without knowing, if the spline was set somewhere else. I suggest that we add a corresponding `else` block in `perform_relaxation` that explicitly sets the spline parameters to `None` when they were not specified

Perhaps both these issues can be solved if the leaded array of spline values ( both `xs`, and `ydys` ) is stored in the python class of the calculation ? like `self.rff_xs`, `self.rff_ydys` ? 

Or maybe another solution can be to define python 

```
class HermiteSpline:
     __init__(fname):
    # .... load spline from file ...
     self.xs=xs;
     self.ydys=ydys; 
```

and than add this whole class to as a property of class calculation like `self.tip_spline = HermiteSpline('tip_spline.dat') `
?

What do you think ?

**Comment by NikoOinonen** [comment]
> It was probably working as long as unitialized variable i=0.

Yes, it seemed that way when I ran it in the debugger, it was `i=0` most of the time, but sometimes randomly it was some large number and then it failed. It was anyways interesting, I learned how to run python in `gdb` while doing this.

> Perhaps both these issues can be solved if the leaded array of spline values ( both xs, and ydys ) is stored in the python class of the calculation ? like self.rff_xs, self.rff_ydys ?

Yes, this sounds like a good idea. Do you want to implement it or should I? I think we want to fix this rather soon, since it's causing some crashes in places.

**Comment by ProkopHapala** [comment]
> Yes, this sounds like a good idea. Do you want to implement it or should I? I think we want to fix this rather soon, since it's causing some crashes in places.

Definitely, if you do it I will be happy. But I feel like I pass to much stuff to you.
