### ISSUE TITLE
FDBM (Full-density based method) broken by recent changes

### ISSUE THREAD

**Issue by mondracek** [Probe-Particle/ppafm#312]
The electrostatic and vdW calculations do not currently work in FDBM, as you can test e.g. with the `ppafm/examples/pyridineDensOverlap/` example.

Running `ppafm-generate-elff -i sample/LOCPOT.xsf --tip_dens tip/CHGCAR.xsf --Rcore 0.7 --doDensity` leads to the error message
``NameError: name 'parameters' is not defined`` 
issued inside the `ppafm/ppafm/HighLevel.py/getAtomsWhichTouchPBCcell` function when trying to call
``atoms, nDim, lvec = io.loadGeometry(fname, format=geometry_format, parameters=parameters)``

Similarly, calling `ppafm-generate-dftd3 -i sample/LOCPOT.xsf --df_name PBE` gives
``ValueError: Please provide the parameters dictionary here``,
raised inside the `loadGeometry` function itself, after this function has been called from `ppafm/HighLevel.py/computeDFTD3` by the line
``atoms, nDim, lvec = io.loadGeometry(input_file, format=geometry_format, parameters=parameters)``

**Comment by NikoOinonen** [comment]
We probably should add the pyridine example into the CI tests to make sure this does not happen again.

**Comment by yakutovicha** [comment]
> We probably should add the pyridine example into the CI tests to make sure this does not happen again.

Thanks, @NikoOinonen, I assume you are referring to [this one](https://github.com/Probe-Particle/ppafm/tree/main/examples/pyridineDensOverlap)?

**Comment by NikoOinonen** [comment]
> Thanks, @NikoOinonen, I assume you are referring to [this one](https://github.com/Probe-Particle/ppafm/tree/main/examples/pyridineDensOverlap)?

@yakutovicha Yes, exactly.

**Comment by yakutovicha** [comment]
> > Thanks, @NikoOinonen, I assume you are referring to [this one](https://github.com/Probe-Particle/ppafm/tree/main/examples/pyridineDensOverlap)?
> 
> @yakutovicha Yes, exactly.

done in https://github.com/Probe-Particle/ppafm/pull/316/commits/e45868a281c4f00f6fad949fedff2c02a5c600d4
