### ISSUE TITLE
Release package on PyPi.

### ISSUE THREAD

**Issue by yakutovicha** [Probe-Particle/ppafm#33]
As soon as the name is chosen (#31), I will book the name on PyPI.

[UPDATE]
One cannot book a name. The only way to keep the package name is by releasing it on PyPi.

**Comment by yakutovicha** [comment]
Here it is: https://pypi.org/project/ppafm/0.1.0/

@ProkopHapala, @ondrejkrejci, @NikoOinonen please share with me your pypi.org usernames - I will add you to the list of maintainers of the repository.

one can now do
```bash
$ pip install ppafm
```
to get the repository

**Comment by NikoOinonen** [comment]
@yakutovicha My user name on pypi is nikooin.

I just tried the installation and it seems like it does not include the subdirectories `defaults`, `ml`, and `ocl`. They are not even in the .tar.gz source file.

**Comment by yakutovicha** [comment]
> @yakutovicha My user name on pypi is nikooin.

You are now invited 👍 

> I just tried the installation and it seems like it does not include the subdirectories `defaults`, `ml`, and `ocl`. They are not even in the .tar.gz source file.

Good catch, thanks @NikoOinonen. I think this can be fixed by adding `__init__.py`files to those folders. Otherwise, Python doesn't consider them as modules. Can you please take care of that?

**Comment by ondrejkrejci** [comment]
@yakutovicha - my user name on pypi is **krejcio1** .

**Comment by yakutovicha** [comment]
> @yakutovicha - my user name on pypi is **krejcio1** .

invited 👍

**Comment by yakutovicha** [comment]
btw, if you want me to add you to `test.pypi.org` - please make your accounts there as well (preferably with the same username as on `pypi.org`)

**Comment by NikoOinonen** [comment]
> Of course, it still won't work properly, as I do not yet know how to manage the C++ part in the PyPI context. But we will get there.

I tested running the pip installed version and it complains with 
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/work/.local/lib/python3.10/site-packages/cpp'
```
which is quite natural, since the JIT compilation is hard-coded to look for the C++ files in a parent directory of the package here https://github.com/Probe-Particle/ProbeParticleModel/blob/c8c6f1a253abbfdff671c6384c1525f50e226d13/ppafm/cpp_utils.py#L11
One simple way of making it work with the JIT compilation would be to just move the `cpp` folder inside the `ppafm` package and distribute the files along with it.

**Comment by yakutovicha** [comment]
@mondracek please share your username as well.

**Comment by yakutovicha** [comment]
For the record: @ProkopHapala  was added to PyPi.

**Comment by mondracek** [comment]
My user name for PyPi is ondracek

**Comment by yakutovicha** [comment]
> ondracek

the invitation was sent 👍

**Comment by mondracek** [comment]
@yakutovicha  And I have accepted!
