### ISSUE TITLE
missing automatic loading of FHI-aims geometry.in and VASP POSCAR files 

### ISSUE THREAD

**Issue by ondrejkrejci** [Probe-Particle/ppafm#39]
`pyProbeParticle/basUtils.py` - `loadGeometry(fname=None,params=None)`
https://github.com/Probe-Particle/ProbeParticleModel/blob/a97b04adcfea4228384c4bd946001599c34b4a83/pyProbeParticle/basUtils.py#L440 
no flag for something like **is_in** - meaning is geometry.in file from FHI-aims. It could have names ending on _.in_ or _.in.next_step_.
there is a procedure for reading the geometry.in files here: 
`loadGeometryIN`
https://github.com/Probe-Particle/ProbeParticleModel/blob/a97b04adcfea4228384c4bd946001599c34b4a83/pyProbeParticle/basUtils.py#L130
If file is named _POSCAR_ or _CONTCAR_ we can use this procedure:
`loadPOSCAR`
https://github.com/Probe-Particle/ProbeParticleModel/blob/a97b04adcfea4228384c4bd946001599c34b4a83/pyProbeParticle/basUtils.py#L149
We just need to be sure, that the _atoms_ format (`xyzs` in case of these 2 procedures) is the same as for the other procedures used in loadGeometry.

**Comment by NikoOinonen** [comment]
Maybe `loadGeometry` should have another argument called `format` that you could use to by-pass the identification from file extension. That way you can put additional extensions like `.next_step` to any file format if you manually specify what the actual format is by the argument.

**Comment by yakutovicha** [comment]
Sorry for repeating myself, but it does seem to me that switching to ASE could solve this also.

**Comment by mondracek** [comment]
I suggest we (actually, I am gonna do it next week, hopefully) try to resolve the issue by a simple patch for now, in a way @ondrejkrejci proposed above: adding a tag ``is_in`` to ``io.py`` for the ``*.in`` and ``*.in.next_step`` geometry files and also something like ``is_vaspcar`` if the file name begins with ``POSCAR*`` or ``CONTCAR*``. I would also add the ``format`` argument as suggested by @NikoOinonen in case the identification by file name fails. (Should it be ``--geometry_format`` or just ``--format`` or something else?) We can switch to ASE later if there is more demand for that.

**Comment by NikoOinonen** [comment]
I think I was originally thinking that it would be something like
```python
def loadGeometry(fname=None, params=None, format=None):
    ...
    if format is None:
        format = inferFromFileExtension(fname)

    if format == 'in':
        geom = loadGeometryIN(fname)
    elif format == 'vaspcar':
        geom = loadPOSCAR(fname)
        ... # And all other formats
    else:
        raise ValueError('Invalid file format')
    ...
```
That way you get away with a single added argument that can be directly passed from the script, and it's easy to add new file formats later.
