### ISSUE TITLE
Minimum supported Python version.

### ISSUE THREAD

**Issue by yakutovicha** [Probe-Particle/ppafm#63]
When releasing a package, we are requested to define a minimum supported Python version. Version 3.7 is still supported, but as of now, it will be [discontinued in 6 months](https://endoflife.date/python).

I would go ahead and set it to Python3.8. Many packages did that already. Any objections?

**Comment by NikoOinonen** [comment]
Sounds good to me.

**Comment by ondrejkrejci** [comment]
I would go with the lower version such as 3.6, just to have support for older machines ...

**Comment by yakutovicha** [comment]
@ProkopHapala, what is your minimum preferred version? So far, 3.6 is the lowest.

**Comment by ProkopHapala** [comment]
Python 3.6 is OK for me.

**Comment by yakutovicha** [comment]
ok, 3.6 it is then.
