### ISSUE TITLE
GUI dependencies into pyproject.toml

### ISSUE THREAD

**Issue by ondrejkrejci** [Probe-Particle/ppafm#64]
Adding PyQt5 into pyproject.toml .

**Comment by yakutovicha** [comment]
Are there any other dependencies one might think of, @NikoOinonen?

**Comment by NikoOinonen** [comment]
I remember before when I tried installing the GUI on a fresh Ubuntu installation (virtual machine), I had an issue where simply installing `PyQt5` with pip did not work. I only got it working by installing it from the Ubuntu repository with
```bash
sudo apt install python3-pyqt5
```
So there might be some other dependence missing with the pip installation. I can look into it again soon.

There also seems to be a dependency on `pillow` in https://github.com/Probe-Particle/ppafm/blob/736972219fe988119f1f020c5893844610ba0707/GUI/ExpShifter.py#L27

**Comment by NikoOinonen** [comment]
Ok, so I tested this again on a fresh Ubuntu install (22.10). Simply installing `PyQt5` from pip does not work. If you try to run the GUI, you get this error
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```
It can be made to work by installing an additional package
```
sudo apt install libxcb-xinerama0
```
I did not find a way to install this with just pip.

So, there are two options, either we add `PyQt5` as a dependency, and the installation will be
```bash
sudo apt install python3-pip libxcb-xinerama0
pip install ppafm
```
or we don't and the installation works with
```bash
sudo apt install python3-pip python3-pyqt5
pip install ppafm
```
I would say the simpler solution is not to add the dependency and tell users to install `python3-pyqt5` if they want to use the GUI.

**Comment by yakutovicha** [comment]
Both options are fine with me. But please make sure to properly document this in the readme.

**Comment by ondrejkrejci** [comment]
Ok, good to know. I would maybe add the second option, as GUI is not essential. But it is needed. I agree with @yakutovicha - we have to document it proprely.
I will try how PyQT5 is working on windows (#27 ), as we probably have the most of GUI users on Windows. Hopefully next week.

**Comment by NikoOinonen** [comment]
The README currently has this:
```
sudo apt install git python3-pip python3-pyqt5
pip install matplotlib numpy pyopencl reikna ase
```
which should work for the moment. We should update it when the `ppafm` pip package is actually functional and comes with the GUI.

**Comment by NikoOinonen** [comment]
I'll add that Anaconda also works without any system packages:
```
conda create -n ppm -c conda-forge python=3.10 numpy matplotlib ase pyopencl reikna ocl-icd-system pillow pyqt make gxx
```
This could be an option in cases where you don't have rights to install system packages, but it's generally less convenient since you need to activate the environment every time you want to use the GUI.
