### ISSUE TITLE
Mac install issue 

### ISSUE THREAD

**Issue by punkpony** [Probe-Particle/ppafm#69]
Hi, 

may be a bit of dumb Q and I missed something essential somewhere. 

Could you advise with the error during installation on a Mac?

I have updated my g++ 10 be 10.4.0 and my clang is 13.0.0\
I have edited the `./cpp/MakeFile` to use  g++-10 compiler,\
then running 'make' gives me the following error:

```
g++-10 -fPIC -std=c++11 -O2 -march=native -mtune=native -c FARFF.cpp -o FARFF.o
In file included from FARFF.h:38,
                 from FARFF.cpp:9:
Draw3D.cpp:9:10: fatal error: SDL2/SDL.h: No such file or directory
    9 | #include <SDL2/SDL.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [FARFF.o] Error 1
```

Thank you! 
V

**Comment by punkpony** [comment]
Thank you for this suggestion. It seems I have SLD2 already, but that did not solve it:

```
 ❯❯❯ brew install SDL2                                                                                                      ✘ 2 
Warning: sdl2 2.26.2 is already installed and up-to-date.
To reinstall 2.26.2, run:
  brew reinstall sdl2

 ❯❯❯ make
g++-10 -fPIC -std=c++11 -O2 -march=native -mtune=native -c FARFF.cpp -o FARFF.o
In file included from FARFF.h:38,
                 from FARFF.cpp:9:
Draw3D.cpp:9:10: fatal error: SDL2/SDL.h: No such file or directory
    9 | #include <SDL2/SDL.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [FARFF.o] Error 1
```

But it indeed was not included correctly, so I put it into the`Makefile`, as:
`CPPFLAGS= -fPIC -std=c++11 -O2 -march=native -mtune=native -I/usr/local/Cellar/sdl2/2.26.2/include/`

which got me further, but still stuck with `FARFF_`:
```
g++-10 -shared FARFF.o -o FARFF_lib.so
Undefined symbols for architecture x86_64:
  "_glBegin", referenced from:
      __ZN6Draw3D13planarPolygonEiPKiPK5Vec3TIdE.part.0 in FARFF.o
      __ZN6Draw3D4textEPKcifi in FARFF.o
      __ZN6Draw3D4textEPKcif5Vec2TIiE in FARFF.o
      __ZN6Draw3D5pointERK5Vec3TIfE in FARFF.o
      __ZN6Draw3D10pointCrossERK5Vec3TIfEf in FARFF.o
      __ZN6Draw3D10pointCrossERK5Vec3TIfEd in FARFF.o
      __ZN6Draw3D3vecERK5Vec3TIfE in FARFF.o
      ...
...
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [FARFF.o] Error 1
```

I thought there was a problem with the linking and also included `-lstdc++` flag, but that doesn't seem to solve this:( 

I am not sure what to try, so any suggestion would be great!

TA!

**Comment by yakutovicha** [comment]
@punkpony, can you please pull the latest changes and try again? It could be we accidentally fixed the issue you reported.

As a side remark: I tried to compile the code on my mac (with an Intel processor) and on my mac at work (Apple M1) - both worked fine 👍

**Comment by yakutovicha** [comment]
Since no further problems were reported, I mark this issue as resolved. Feel free to reopen it in case the issue persists.
