### ISSUE TITLE
pyridineDensOverlap example broken

### ISSUE THREAD

**Issue by ondrejkrejci** [Probe-Particle/ppafm#70]
https://github.com/Probe-Particle/ppafm/tree/main/examples/pyridineDensOverlap test
while running:
`python3 $PPPATH/generateElFF.py -i sample/LOCPOT.xsf --tip_dens tip/CHGCAR.xsf --Rcore 0.7 -E`
I have obtained this error:
```
Traceback (most recent call last):
  File "../..//generateElFF.py", line 101, in <module>
    PPH.subtractCoreDensities( rho_tip, lvec_tip, elems=elems_tip, Rs=Rs_tip, valElDict=valElDict, Rcore=options.Rcore, head=head_tip )
NameError: name 'elems_tip' is not defined
```

**Comment by NikoOinonen** [comment]
I also ran into this while testing it comparing to the OCL version. It should work if you just add ` --doDensity` to the command. @ProkopHapala maybe you can confirm that this is right?

**Comment by ProkopHapala** [comment]
I corrected the error now while I was testing vdW damping functions. Also there were wrong links to my mega.nz for downloading sample CHGCAR na LOCPOT. I updated the links. 

It would be nice if somebody else can try it to see if can reproduce the results as well.

**Comment by ProkopHapala** [comment]
this issue should be solved also in this pull request
https://github.com/Probe-Particle/ppafm/pull/87

**Comment by ProkopHapala** [comment]
@ondrejkrejci I see this issue is still open, although I changed status to `Done`. I don't see how to close it, maybe you can?
