### ISSUE TITLE
Generator example not doing anything and corrupted

### ISSUE THREAD

**Issue by ondrejkrejci** [Probe-Particle/ppafm#72]
https://github.com/Probe-Particle/ppafm/tree/main/examples/Generator
_run.sh_ error:
```
/usr/bin/python3: No module named ppafm.GeneratorOCL_Simple
```
_run_afmulator.sh_ doing nothing ...

**Comment by NikoOinonen** [comment]
Both the generator and the AFMulator examples were outdated, so I deleted them while moving around and cleaning the code recently. The `run.sh` and `run_afmulator.sh` are remnants of that, and I would just delete them. The `test_trainer.py` script should still be working, but it would probably need more comments to serve as a good example.
