### ISSUE TITLE
Code compilation during pip install

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#75]
The C++ code needs to be compiled during pip installation instead of on the fly.

**Comment by NikoOinonen** [comment]
I have managed to make it so that the C++ compilation is done during the building of the pip wheel so that the shared library (.so) files are included in the distribution. We originally discussed that it's also possible to make the compilation happen during the pip install, but it probably does not make a big difference? Any opinion @yakutovicha 

There is also a conflict now with how we want to do the compilation. For the basic user it's better if the code is already compiled during runtime, but for development it's nice to have the code automatically recompile. I suggest we add a check on an environment variable, call it `PPAFM_RECOMPILE`, and if it's set, the code is recompiled, otherwise use the already compiled files. Maybe @ProkopHapala @ondrejkrejci could give their opinions?

**Comment by ProkopHapala** [comment]
> For the basic user it's better if the code is already compiled during runtime, but for development it's nice to have the code automatically recompile. I suggest we add a check on an environment variable, call it PPAFM_RECOMPILE, and if it's set, the code is recompiled, otherwise use the already compiled files.

I completely agree there should be some switch for user/developer if it recompiles or not. Not sure if environment varaible is the best, or there could be some switch inside the code. I'm not very used to use environement variables but maybe it is better solution, because changing flag inside the code would be tracket by git changes.

**Comment by NikoOinonen** [comment]
@ProkopHapala I also wanted to ask, what is this `libRigidMol.so_` binary blob without source code in https://github.com/Probe-Particle/ppafm/tree/main/bin? Should it be included in the pip installation?

**Comment by ProkopHapala** [comment]
> I also wanted to ask, what is this libRigidMol.so_ binary blob without source code

Thanks for pointing out. I used my rigid-body-dynamics code (source code is in different project) to relax molecules on substrate when we were doing images of Campher molecule. See related code here:
https://github.com/Probe-Particle/ppafm/blob/main/ppafm/SurfConf.py
https://github.com/Probe-Particle/ppafm/blob/main/ppafm/RigidMol.py

It is quite a nieche use case, and probably not worth to be part of `ppafm`

Notice that at some point I wanted to make ppafm some comprehensive tool including molecular builder and classical moleculer dynamics of molecules on surface. But now I have this new project (https://github.com/ProkopHapala/FireCore) for that purpose, so perhaps it make sense to remove this stuff from ppafm.

**Comment by ProkopHapala** [comment]
> It is quite a nieche use case, ... so perhaps it make sense to remove this stuff from ppafm.

Perhaps we should make another sweep inside ppafm python module folder and make a sub-module `dev` here, where we pus such staff wich we do not want to directly remove, but which are not esential

By quick look I think following modules fall into that cathegory:

https://github.com/Probe-Particle/ppafm/blob/main/ppafm/CG.py
https://github.com/Probe-Particle/ppafm/blob/main/ppafm/COvsCO.py
https://github.com/Probe-Particle/ppafm/blob/main/ppafm/FARFF.py
https://github.com/Probe-Particle/ppafm/blob/main/ppafm/GLView.py
https://github.com/Probe-Particle/ppafm/blob/main/ppafm/MMFF.py
https://github.com/Probe-Particle/ppafm/blob/main/ppafm/Multipoles.py
https://github.com/Probe-Particle/ppafm/blob/main/ppafm/PolyCycles.py
https://github.com/Probe-Particle/ppafm/blob/main/ppafm/ReactiveFF.py
https://github.com/Probe-Particle/ppafm/blob/main/ppafm/RigidMol.py
https://github.com/Probe-Particle/ppafm/blob/main/ppafm/SimplePot.py
https://github.com/Probe-Particle/ppafm/blob/main/ppafm/SurfConf.py
https://github.com/Probe-Particle/ppafm/blob/main/ppafm/atomfit.py
https://github.com/Probe-Particle/ppafm/blob/main/ppafm/RigidMol.py

**Comment by ProkopHapala** [comment]
> By quick look I think following modules fall into that cathegory:

The same can be said for thise related C++ modules:

Various forcefields which are not used in main code:
https://github.com/Probe-Particle/ppafm/blob/main/cpp/COvsCO.cpp 
https://github.com/Probe-Particle/ppafm/blob/main/cpp/FARFF.cpp
https://github.com/Probe-Particle/ppafm/blob/main/cpp/FARFF.h
https://github.com/Probe-Particle/ppafm/blob/main/cpp/MMFF.cpp
https://github.com/Probe-Particle/ppafm/blob/main/cpp/MMFFBuilder.h
https://github.com/Probe-Particle/ppafm/blob/main/cpp/MMFF.h
https://github.com/Probe-Particle/ppafm/blob/main/cpp/PolyCycles.cpp
https://github.com/Probe-Particle/ppafm/blob/main/cpp/PolyCycles.h
https://github.com/Probe-Particle/ppafm/blob/main/cpp/NBFF.h
https://github.com/Probe-Particle/ppafm/blob/main/cpp/QEq.h
https://github.com/Probe-Particle/ppafm/blob/main/cpp/RARFFarr.h
https://github.com/Probe-Particle/ppafm/blob/main/cpp/ReactiveFF.cpp
https://github.com/Probe-Particle/ppafm/blob/main/cpp/SimplePot.cpp

Some fitting and optimization utilities:
https://github.com/Probe-Particle/ppafm/blob/main/cpp/CG.h
https://github.com/Probe-Particle/ppafm/blob/main/cpp/DynamicOpt.h
https://github.com/Probe-Particle/ppafm/blob/main/cpp/Multipoles.cpp
https://github.com/Probe-Particle/ppafm/blob/main/cpp/atomfit.cpp

Real time OpenGL visualization of molecules: 
https://github.com/Probe-Particle/ppafm/blob/main/cpp/GLView.cpp
https://github.com/Probe-Particle/ppafm/blob/main/cpp/Camera.h
https://github.com/Probe-Particle/ppafm/blob/main/cpp/Draw3D.cpp
https://github.com/Probe-Particle/ppafm/blob/main/cpp/Draw3D.h

**Comment by NikoOinonen** [comment]
@ProkopHapala Then if it's okay, I can move those .py files to a `dev` subfolder inside `ppafm` and exclude that whole folder as well as those C++ files from the pip installation as a part of this PR.

**Comment by ProkopHapala** [comment]
> @ProkopHapala Then if it's okay, I can move those .py files to a `dev` subfolder inside `ppafm` and exclude that whole folder as well as those C++ files from the pip installation as a part of this PR.

yes, I think it should be OK

**Comment by NikoOinonen** [comment]
> I completely agree there should be some switch for user/developer if it recompiles or not. Not sure if environment varaible is the best, or there could be some switch inside the code. I'm not very used to use environement variables but maybe it is better solution, because changing flag inside the code would be tracket by git changes.

@ProkopHapala Using an environment variable gives a lot of flexibility in choosing where you want to apply it. You could set it globally in your .bashrc (or equivalent), you could set it inside a run script, or even for a single run like
```bash
PPAFM_RECOMPILE=1 ./run.sh
```
I don't see clear opposition to the idea, so I'm going to go ahead and implement it like this.

**Comment by NikoOinonen** [comment]
> I have managed to make it so that the C++ compilation is done during the building of the pip wheel so that the shared library (.so) files are included in the distribution. We originally discussed that it's also possible to make the compilation happen during the pip install, but it probably does not make a big difference? Any opinion @yakutovicha

Actually, looking at the documentation, pip can install a package both from a pre-built wheel and a source distribution: https://packaging.python.org/en/latest/tutorials/installing-packages/#source-distributions-vs-wheels. When you build the wheel with `python -m build`, it also creates the source distribution in `ppafm-[version].tar.gz`. If we put both of these into PyPI, then the package can either be installed with the pre-built wheel or compiled on install. Numpy, for example, also has both wheels and the source distribution: https://pypi.org/project/numpy/#files.

**Comment by NikoOinonen** [comment]
While figuring out the compilation steps, I also managed to make it compile on Windows by using the Microsoft `cl` compiler tool from the Visual Studio build tools. It required modifying the C++ source files in some parts, because the Microsoft C-compiler seems to be more standards compliant and does not allow some things that GCC does. But it's possible to build a pip wheel and run it on Windows natively as well if we want to. The GUI works as well.

**Comment by ProkopHapala** [comment]
> But it's possible to build a pip wheel and run it on Windows natively

Great! 

>  It required modifying the C++ source files in some parts, because the Microsoft C-compiler seems to be more standards compliant and does not allow some things that GCC does.

like what, for example ?

**Comment by NikoOinonen** [comment]
@ProkopHapala You can see these two commits:
https://github.com/Probe-Particle/ppafm/commit/444920521210ed334877c53d2389015dcd1dffbf
https://github.com/Probe-Particle/ppafm/commit/2b7f65d8e8a27c1973e4f04bb9aecb5ec99fbfd6

The main things were that the `d` identifier for doubles is optional in GCC and not allowed on the Microsoft compiler, since double is the default precision for floats, and there was a thing with struct initialization syntax not allowing the parenthesis around the struct name.

Additionally, I had to add this `__declspec(dllexport)` thing in front of all functions that are imported into Python, because otherwise ctypes does not find them on Windows.

**Comment by ondrejkrejci** [comment]
@NikoOinonen: 
> I have managed to make it so that the C++ compilation is done during the building of the pip wheel so that the shared library (.so) files are included in the distribution. We originally discussed that it's also possible to make the compilation happen during the pip install, but it probably does not make a big difference?

I am wondering if it is the same way as **numpy** has it? There is no installation needed on any machine ... 

> Using an environment variable gives a lot of flexibility in choosing where you want to apply it. You could set it globally in your .bashrc (or equivalent), you could set it inside a run script, or even for a single run like `PPAFM_RECOMPILE=1 ./run.sh` ; I don't see clear opposition to the idea, so I'm going to go ahead and implement it like this.

Great, I got it ... 

> The main things were that the `d` identifier for doubles is optional in GCC and not allowed on the Microsoft compiler, since double is the default precision for floats, and there was a thing with struct initialization syntax not allowing the parenthesis around the struct name.

This was also known issue with the official gcc compiler for MAC for a long time.

Otherwise good work. The only problem with the Visual Studio was that my privilages did not allowed it to install for me.
