### ISSUE TITLE
Using the aliases of builtin types like `numpy.int` is deprecated

### ISSUE THREAD

**Issue by yakutovicha** [Probe-Particle/ppafm#76]
In #56 I had to fix the upper version of numpy (see the [numpy deprecation note](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations)) due to the removal of `numpy.int`, `numpy.float`, etc.

We need to fix the code according to the [guidelines](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated) and unblock the version again.

**Comment by NikoOinonen** [comment]
I can take care of this.
