### ISSUE TITLE
Non-ASCII character(s) in example params.ini

### ISSUE THREAD

**Issue by mondracek** [Probe-Particle/ppafm#89]
Oh well, why things that work out of the box for anyone else never work for me.. I am struggling to get the new ppafm code running, so expect a series of issues I stumble over in the process. The first is gonna be an easy one: When running examples from ``ProbeParticleModel/examples``, the code crashes while reading the provided ``params.ini``, complaining about a non-ASCII character. The offending character is the *angstrom* sign, so the solution is simply to remove it or replace by the string ``angstrom`` or something similar. Has anyone else encountered this? If the problem is just some idiosyncrasy of the particular environment on my machine, I can just change the ``params.ini`` files locally for myself, but if there is a danger this is going to affect more users, I should push the modified examples to the repo.

**Comment by NikoOinonen** [comment]
@mondracek Can you post the exact error traceback that you get. Python should be using utf-8 encoding by default, so it should work with non-ascii characters.

**Comment by mondracek** [comment]
The error message is in the attached err.txt file here.
[err.txt](https://github.com/Probe-Particle/ppafm/files/10786804/err.txt)
But I have just found out that the occurrence of the error depends on the node on which I am running the calculation, so maybe you can ignore it and I will try to solve it with the administrators of our computer grid. Shall we close the issue then?

**Comment by NikoOinonen** [comment]
A quick search suggest that you could have some locale issue on some of the nodes: https://stackoverflow.com/a/51027262. So yes, you could try to figure it out with your admins, and you can reopen the issue if there is something we need to fix.
